package com.jerry.banquet.model;

import java.util.Date;

public class TBanquetOrderTemplate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_order_template.templateId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String templateid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_order_template.restaurantId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String restaurantid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_order_template.templateType
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Integer templatetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_order_template.templateName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String templatename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_order_template.isValid
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Integer isvalid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_order_template.createTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_order_template.createUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String createuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_order_template.createUserName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String createusername;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_order_template.templateId
     *
     * @return the value of t_banquet_order_template.templateId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getTemplateid() {
        return templateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_order_template.templateId
     *
     * @param templateid the value for t_banquet_order_template.templateId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setTemplateid(String templateid) {
        this.templateid = templateid == null ? null : templateid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_order_template.restaurantId
     *
     * @return the value of t_banquet_order_template.restaurantId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getRestaurantid() {
        return restaurantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_order_template.restaurantId
     *
     * @param restaurantid the value for t_banquet_order_template.restaurantId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setRestaurantid(String restaurantid) {
        this.restaurantid = restaurantid == null ? null : restaurantid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_order_template.templateType
     *
     * @return the value of t_banquet_order_template.templateType
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Integer getTemplatetype() {
        return templatetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_order_template.templateType
     *
     * @param templatetype the value for t_banquet_order_template.templateType
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setTemplatetype(Integer templatetype) {
        this.templatetype = templatetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_order_template.templateName
     *
     * @return the value of t_banquet_order_template.templateName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getTemplatename() {
        return templatename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_order_template.templateName
     *
     * @param templatename the value for t_banquet_order_template.templateName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setTemplatename(String templatename) {
        this.templatename = templatename == null ? null : templatename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_order_template.isValid
     *
     * @return the value of t_banquet_order_template.isValid
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Integer getIsvalid() {
        return isvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_order_template.isValid
     *
     * @param isvalid the value for t_banquet_order_template.isValid
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setIsvalid(Integer isvalid) {
        this.isvalid = isvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_order_template.createTime
     *
     * @return the value of t_banquet_order_template.createTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_order_template.createTime
     *
     * @param createtime the value for t_banquet_order_template.createTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_order_template.createUserId
     *
     * @return the value of t_banquet_order_template.createUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_order_template.createUserId
     *
     * @param createuserid the value for t_banquet_order_template.createUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setCreateuserid(String createuserid) {
        this.createuserid = createuserid == null ? null : createuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_order_template.createUserName
     *
     * @return the value of t_banquet_order_template.createUserName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getCreateusername() {
        return createusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_order_template.createUserName
     *
     * @param createusername the value for t_banquet_order_template.createUserName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setCreateusername(String createusername) {
        this.createusername = createusername == null ? null : createusername.trim();
    }
}