package com.jerry.banquet.model;

import java.math.BigDecimal;
import java.util.Date;

public class TBanquet {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet.banquetId
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    private String banquetid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet.restaurantId
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    private String restaurantid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet.restaurantName
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    private String restaurantname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet.nicheSource
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    private String nichesource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet.nicheType
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    private String nichetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet.nicheTitle
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    private String nichetitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet.nicheStartTime
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    private Date nichestarttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet.nicheEndTime
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    private Date nicheendtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet.intentMan
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    private String intentman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet.intentMerchMan
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    private String intentmerchman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet.intentPlanTables
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    private Integer intentplantables;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet.intentBudgetPer
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    private Integer intentbudgetper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet.intentRemark
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    private String intentremark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet.priceSetmealId
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    private String pricesetmealid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet.priceSetmealName
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    private String pricesetmealname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet.priceSetmealCur
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    private Integer pricesetmealcur;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet.priceSetmealOri
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    private Integer pricesetmealori;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet.priceAdjustDishNum
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    private Integer priceadjustdishnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet.priceWine
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    private Integer pricewine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet.priceAllocAmount
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    private Integer priceallocamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet.priceServiceCharge
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    private Integer priceservicecharge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet.priceServiceType
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    private String priceservicetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet.priceInvoiceType
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    private String priceinvoicetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet.priceRemark
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    private String priceremark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet.priceAgrDiscType
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    private String priceagrdisctype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet.contractAgrDiscounts
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    private BigDecimal contractagrdiscounts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet.contractAfAmount
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    private BigDecimal contractafamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet.contractFinalAmount
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    private BigDecimal contractfinalamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet.deposit
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    private BigDecimal deposit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet.eoCount
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    private Integer eocount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet.contractGuaTables
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    private Integer contractguatables;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet.contractSpareTables
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    private Integer contractsparetables;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet.contractPayType
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    private String contractpaytype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet.orderStage
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    private Integer orderstage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet.orderStageDate
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    private Date orderstagedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet.orderStatus
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    private Integer orderstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet.createTime
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet.createUserId
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    private String createuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet.createUser
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    private String createuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet.updateTime
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet.updateUserId
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    private String updateuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet.updateUser
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    private String updateuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet.receivableAmount
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    private Integer receivableamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet.discountAmount
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    private Integer discountamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet.collectionTotalAmount
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    private Integer collectiontotalamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet.unpaidAmount
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    private Integer unpaidamount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet.banquetId
     *
     * @return the value of t_banquet.banquetId
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public String getBanquetid() {
        return banquetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet.banquetId
     *
     * @param banquetid the value for t_banquet.banquetId
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public void setBanquetid(String banquetid) {
        this.banquetid = banquetid == null ? null : banquetid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet.restaurantId
     *
     * @return the value of t_banquet.restaurantId
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public String getRestaurantid() {
        return restaurantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet.restaurantId
     *
     * @param restaurantid the value for t_banquet.restaurantId
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public void setRestaurantid(String restaurantid) {
        this.restaurantid = restaurantid == null ? null : restaurantid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet.restaurantName
     *
     * @return the value of t_banquet.restaurantName
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public String getRestaurantname() {
        return restaurantname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet.restaurantName
     *
     * @param restaurantname the value for t_banquet.restaurantName
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public void setRestaurantname(String restaurantname) {
        this.restaurantname = restaurantname == null ? null : restaurantname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet.nicheSource
     *
     * @return the value of t_banquet.nicheSource
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public String getNichesource() {
        return nichesource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet.nicheSource
     *
     * @param nichesource the value for t_banquet.nicheSource
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public void setNichesource(String nichesource) {
        this.nichesource = nichesource == null ? null : nichesource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet.nicheType
     *
     * @return the value of t_banquet.nicheType
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public String getNichetype() {
        return nichetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet.nicheType
     *
     * @param nichetype the value for t_banquet.nicheType
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public void setNichetype(String nichetype) {
        this.nichetype = nichetype == null ? null : nichetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet.nicheTitle
     *
     * @return the value of t_banquet.nicheTitle
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public String getNichetitle() {
        return nichetitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet.nicheTitle
     *
     * @param nichetitle the value for t_banquet.nicheTitle
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public void setNichetitle(String nichetitle) {
        this.nichetitle = nichetitle == null ? null : nichetitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet.nicheStartTime
     *
     * @return the value of t_banquet.nicheStartTime
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public Date getNichestarttime() {
        return nichestarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet.nicheStartTime
     *
     * @param nichestarttime the value for t_banquet.nicheStartTime
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public void setNichestarttime(Date nichestarttime) {
        this.nichestarttime = nichestarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet.nicheEndTime
     *
     * @return the value of t_banquet.nicheEndTime
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public Date getNicheendtime() {
        return nicheendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet.nicheEndTime
     *
     * @param nicheendtime the value for t_banquet.nicheEndTime
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public void setNicheendtime(Date nicheendtime) {
        this.nicheendtime = nicheendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet.intentMan
     *
     * @return the value of t_banquet.intentMan
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public String getIntentman() {
        return intentman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet.intentMan
     *
     * @param intentman the value for t_banquet.intentMan
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public void setIntentman(String intentman) {
        this.intentman = intentman == null ? null : intentman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet.intentMerchMan
     *
     * @return the value of t_banquet.intentMerchMan
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public String getIntentmerchman() {
        return intentmerchman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet.intentMerchMan
     *
     * @param intentmerchman the value for t_banquet.intentMerchMan
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public void setIntentmerchman(String intentmerchman) {
        this.intentmerchman = intentmerchman == null ? null : intentmerchman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet.intentPlanTables
     *
     * @return the value of t_banquet.intentPlanTables
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public Integer getIntentplantables() {
        return intentplantables;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet.intentPlanTables
     *
     * @param intentplantables the value for t_banquet.intentPlanTables
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public void setIntentplantables(Integer intentplantables) {
        this.intentplantables = intentplantables;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet.intentBudgetPer
     *
     * @return the value of t_banquet.intentBudgetPer
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public Integer getIntentbudgetper() {
        return intentbudgetper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet.intentBudgetPer
     *
     * @param intentbudgetper the value for t_banquet.intentBudgetPer
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public void setIntentbudgetper(Integer intentbudgetper) {
        this.intentbudgetper = intentbudgetper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet.intentRemark
     *
     * @return the value of t_banquet.intentRemark
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public String getIntentremark() {
        return intentremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet.intentRemark
     *
     * @param intentremark the value for t_banquet.intentRemark
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public void setIntentremark(String intentremark) {
        this.intentremark = intentremark == null ? null : intentremark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet.priceSetmealId
     *
     * @return the value of t_banquet.priceSetmealId
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public String getPricesetmealid() {
        return pricesetmealid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet.priceSetmealId
     *
     * @param pricesetmealid the value for t_banquet.priceSetmealId
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public void setPricesetmealid(String pricesetmealid) {
        this.pricesetmealid = pricesetmealid == null ? null : pricesetmealid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet.priceSetmealName
     *
     * @return the value of t_banquet.priceSetmealName
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public String getPricesetmealname() {
        return pricesetmealname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet.priceSetmealName
     *
     * @param pricesetmealname the value for t_banquet.priceSetmealName
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public void setPricesetmealname(String pricesetmealname) {
        this.pricesetmealname = pricesetmealname == null ? null : pricesetmealname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet.priceSetmealCur
     *
     * @return the value of t_banquet.priceSetmealCur
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public Integer getPricesetmealcur() {
        return pricesetmealcur;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet.priceSetmealCur
     *
     * @param pricesetmealcur the value for t_banquet.priceSetmealCur
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public void setPricesetmealcur(Integer pricesetmealcur) {
        this.pricesetmealcur = pricesetmealcur;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet.priceSetmealOri
     *
     * @return the value of t_banquet.priceSetmealOri
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public Integer getPricesetmealori() {
        return pricesetmealori;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet.priceSetmealOri
     *
     * @param pricesetmealori the value for t_banquet.priceSetmealOri
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public void setPricesetmealori(Integer pricesetmealori) {
        this.pricesetmealori = pricesetmealori;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet.priceAdjustDishNum
     *
     * @return the value of t_banquet.priceAdjustDishNum
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public Integer getPriceadjustdishnum() {
        return priceadjustdishnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet.priceAdjustDishNum
     *
     * @param priceadjustdishnum the value for t_banquet.priceAdjustDishNum
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public void setPriceadjustdishnum(Integer priceadjustdishnum) {
        this.priceadjustdishnum = priceadjustdishnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet.priceWine
     *
     * @return the value of t_banquet.priceWine
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public Integer getPricewine() {
        return pricewine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet.priceWine
     *
     * @param pricewine the value for t_banquet.priceWine
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public void setPricewine(Integer pricewine) {
        this.pricewine = pricewine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet.priceAllocAmount
     *
     * @return the value of t_banquet.priceAllocAmount
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public Integer getPriceallocamount() {
        return priceallocamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet.priceAllocAmount
     *
     * @param priceallocamount the value for t_banquet.priceAllocAmount
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public void setPriceallocamount(Integer priceallocamount) {
        this.priceallocamount = priceallocamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet.priceServiceCharge
     *
     * @return the value of t_banquet.priceServiceCharge
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public Integer getPriceservicecharge() {
        return priceservicecharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet.priceServiceCharge
     *
     * @param priceservicecharge the value for t_banquet.priceServiceCharge
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public void setPriceservicecharge(Integer priceservicecharge) {
        this.priceservicecharge = priceservicecharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet.priceServiceType
     *
     * @return the value of t_banquet.priceServiceType
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public String getPriceservicetype() {
        return priceservicetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet.priceServiceType
     *
     * @param priceservicetype the value for t_banquet.priceServiceType
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public void setPriceservicetype(String priceservicetype) {
        this.priceservicetype = priceservicetype == null ? null : priceservicetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet.priceInvoiceType
     *
     * @return the value of t_banquet.priceInvoiceType
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public String getPriceinvoicetype() {
        return priceinvoicetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet.priceInvoiceType
     *
     * @param priceinvoicetype the value for t_banquet.priceInvoiceType
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public void setPriceinvoicetype(String priceinvoicetype) {
        this.priceinvoicetype = priceinvoicetype == null ? null : priceinvoicetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet.priceRemark
     *
     * @return the value of t_banquet.priceRemark
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public String getPriceremark() {
        return priceremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet.priceRemark
     *
     * @param priceremark the value for t_banquet.priceRemark
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public void setPriceremark(String priceremark) {
        this.priceremark = priceremark == null ? null : priceremark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet.priceAgrDiscType
     *
     * @return the value of t_banquet.priceAgrDiscType
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public String getPriceagrdisctype() {
        return priceagrdisctype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet.priceAgrDiscType
     *
     * @param priceagrdisctype the value for t_banquet.priceAgrDiscType
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public void setPriceagrdisctype(String priceagrdisctype) {
        this.priceagrdisctype = priceagrdisctype == null ? null : priceagrdisctype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet.contractAgrDiscounts
     *
     * @return the value of t_banquet.contractAgrDiscounts
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public BigDecimal getContractagrdiscounts() {
        return contractagrdiscounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet.contractAgrDiscounts
     *
     * @param contractagrdiscounts the value for t_banquet.contractAgrDiscounts
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public void setContractagrdiscounts(BigDecimal contractagrdiscounts) {
        this.contractagrdiscounts = contractagrdiscounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet.contractAfAmount
     *
     * @return the value of t_banquet.contractAfAmount
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public BigDecimal getContractafamount() {
        return contractafamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet.contractAfAmount
     *
     * @param contractafamount the value for t_banquet.contractAfAmount
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public void setContractafamount(BigDecimal contractafamount) {
        this.contractafamount = contractafamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet.contractFinalAmount
     *
     * @return the value of t_banquet.contractFinalAmount
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public BigDecimal getContractfinalamount() {
        return contractfinalamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet.contractFinalAmount
     *
     * @param contractfinalamount the value for t_banquet.contractFinalAmount
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public void setContractfinalamount(BigDecimal contractfinalamount) {
        this.contractfinalamount = contractfinalamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet.deposit
     *
     * @return the value of t_banquet.deposit
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public BigDecimal getDeposit() {
        return deposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet.deposit
     *
     * @param deposit the value for t_banquet.deposit
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public void setDeposit(BigDecimal deposit) {
        this.deposit = deposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet.eoCount
     *
     * @return the value of t_banquet.eoCount
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public Integer getEocount() {
        return eocount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet.eoCount
     *
     * @param eocount the value for t_banquet.eoCount
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public void setEocount(Integer eocount) {
        this.eocount = eocount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet.contractGuaTables
     *
     * @return the value of t_banquet.contractGuaTables
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public Integer getContractguatables() {
        return contractguatables;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet.contractGuaTables
     *
     * @param contractguatables the value for t_banquet.contractGuaTables
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public void setContractguatables(Integer contractguatables) {
        this.contractguatables = contractguatables;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet.contractSpareTables
     *
     * @return the value of t_banquet.contractSpareTables
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public Integer getContractsparetables() {
        return contractsparetables;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet.contractSpareTables
     *
     * @param contractsparetables the value for t_banquet.contractSpareTables
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public void setContractsparetables(Integer contractsparetables) {
        this.contractsparetables = contractsparetables;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet.contractPayType
     *
     * @return the value of t_banquet.contractPayType
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public String getContractpaytype() {
        return contractpaytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet.contractPayType
     *
     * @param contractpaytype the value for t_banquet.contractPayType
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public void setContractpaytype(String contractpaytype) {
        this.contractpaytype = contractpaytype == null ? null : contractpaytype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet.orderStage
     *
     * @return the value of t_banquet.orderStage
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public Integer getOrderstage() {
        return orderstage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet.orderStage
     *
     * @param orderstage the value for t_banquet.orderStage
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public void setOrderstage(Integer orderstage) {
        this.orderstage = orderstage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet.orderStageDate
     *
     * @return the value of t_banquet.orderStageDate
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public Date getOrderstagedate() {
        return orderstagedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet.orderStageDate
     *
     * @param orderstagedate the value for t_banquet.orderStageDate
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public void setOrderstagedate(Date orderstagedate) {
        this.orderstagedate = orderstagedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet.orderStatus
     *
     * @return the value of t_banquet.orderStatus
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public Integer getOrderstatus() {
        return orderstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet.orderStatus
     *
     * @param orderstatus the value for t_banquet.orderStatus
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public void setOrderstatus(Integer orderstatus) {
        this.orderstatus = orderstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet.createTime
     *
     * @return the value of t_banquet.createTime
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet.createTime
     *
     * @param createtime the value for t_banquet.createTime
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet.createUserId
     *
     * @return the value of t_banquet.createUserId
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public String getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet.createUserId
     *
     * @param createuserid the value for t_banquet.createUserId
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public void setCreateuserid(String createuserid) {
        this.createuserid = createuserid == null ? null : createuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet.createUser
     *
     * @return the value of t_banquet.createUser
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet.createUser
     *
     * @param createuser the value for t_banquet.createUser
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser == null ? null : createuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet.updateTime
     *
     * @return the value of t_banquet.updateTime
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet.updateTime
     *
     * @param updatetime the value for t_banquet.updateTime
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet.updateUserId
     *
     * @return the value of t_banquet.updateUserId
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public String getUpdateuserid() {
        return updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet.updateUserId
     *
     * @param updateuserid the value for t_banquet.updateUserId
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public void setUpdateuserid(String updateuserid) {
        this.updateuserid = updateuserid == null ? null : updateuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet.updateUser
     *
     * @return the value of t_banquet.updateUser
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public String getUpdateuser() {
        return updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet.updateUser
     *
     * @param updateuser the value for t_banquet.updateUser
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public void setUpdateuser(String updateuser) {
        this.updateuser = updateuser == null ? null : updateuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet.receivableAmount
     *
     * @return the value of t_banquet.receivableAmount
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public Integer getReceivableamount() {
        return receivableamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet.receivableAmount
     *
     * @param receivableamount the value for t_banquet.receivableAmount
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public void setReceivableamount(Integer receivableamount) {
        this.receivableamount = receivableamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet.discountAmount
     *
     * @return the value of t_banquet.discountAmount
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public Integer getDiscountamount() {
        return discountamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet.discountAmount
     *
     * @param discountamount the value for t_banquet.discountAmount
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public void setDiscountamount(Integer discountamount) {
        this.discountamount = discountamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet.collectionTotalAmount
     *
     * @return the value of t_banquet.collectionTotalAmount
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public Integer getCollectiontotalamount() {
        return collectiontotalamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet.collectionTotalAmount
     *
     * @param collectiontotalamount the value for t_banquet.collectionTotalAmount
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public void setCollectiontotalamount(Integer collectiontotalamount) {
        this.collectiontotalamount = collectiontotalamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet.unpaidAmount
     *
     * @return the value of t_banquet.unpaidAmount
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public Integer getUnpaidamount() {
        return unpaidamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet.unpaidAmount
     *
     * @param unpaidamount the value for t_banquet.unpaidAmount
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    public void setUnpaidamount(Integer unpaidamount) {
        this.unpaidamount = unpaidamount;
    }
}