package com.jerry.banquet.model;

import java.util.Date;

public class TBanquetLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_log.logId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String logid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_log.banquetId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String banquetid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_log.banquetStage
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Integer banquetstage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_log.operationName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String operationname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_log.noteTakerId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String notetakerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_log.noteTakerName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String notetakername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_log.noteDate
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Date notedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_log.content
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_log.createTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_log.createUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String createuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_log.createUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String createuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_log.updateTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_log.updateUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String updateuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_log.updateUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String updateuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_log.logId
     *
     * @return the value of t_banquet_log.logId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getLogid() {
        return logid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_log.logId
     *
     * @param logid the value for t_banquet_log.logId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setLogid(String logid) {
        this.logid = logid == null ? null : logid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_log.banquetId
     *
     * @return the value of t_banquet_log.banquetId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getBanquetid() {
        return banquetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_log.banquetId
     *
     * @param banquetid the value for t_banquet_log.banquetId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setBanquetid(String banquetid) {
        this.banquetid = banquetid == null ? null : banquetid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_log.banquetStage
     *
     * @return the value of t_banquet_log.banquetStage
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Integer getBanquetstage() {
        return banquetstage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_log.banquetStage
     *
     * @param banquetstage the value for t_banquet_log.banquetStage
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setBanquetstage(Integer banquetstage) {
        this.banquetstage = banquetstage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_log.operationName
     *
     * @return the value of t_banquet_log.operationName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getOperationname() {
        return operationname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_log.operationName
     *
     * @param operationname the value for t_banquet_log.operationName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setOperationname(String operationname) {
        this.operationname = operationname == null ? null : operationname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_log.noteTakerId
     *
     * @return the value of t_banquet_log.noteTakerId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getNotetakerid() {
        return notetakerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_log.noteTakerId
     *
     * @param notetakerid the value for t_banquet_log.noteTakerId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setNotetakerid(String notetakerid) {
        this.notetakerid = notetakerid == null ? null : notetakerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_log.noteTakerName
     *
     * @return the value of t_banquet_log.noteTakerName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getNotetakername() {
        return notetakername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_log.noteTakerName
     *
     * @param notetakername the value for t_banquet_log.noteTakerName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setNotetakername(String notetakername) {
        this.notetakername = notetakername == null ? null : notetakername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_log.noteDate
     *
     * @return the value of t_banquet_log.noteDate
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Date getNotedate() {
        return notedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_log.noteDate
     *
     * @param notedate the value for t_banquet_log.noteDate
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setNotedate(Date notedate) {
        this.notedate = notedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_log.content
     *
     * @return the value of t_banquet_log.content
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_log.content
     *
     * @param content the value for t_banquet_log.content
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_log.createTime
     *
     * @return the value of t_banquet_log.createTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_log.createTime
     *
     * @param createtime the value for t_banquet_log.createTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_log.createUserId
     *
     * @return the value of t_banquet_log.createUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_log.createUserId
     *
     * @param createuserid the value for t_banquet_log.createUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setCreateuserid(String createuserid) {
        this.createuserid = createuserid == null ? null : createuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_log.createUser
     *
     * @return the value of t_banquet_log.createUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_log.createUser
     *
     * @param createuser the value for t_banquet_log.createUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser == null ? null : createuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_log.updateTime
     *
     * @return the value of t_banquet_log.updateTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_log.updateTime
     *
     * @param updatetime the value for t_banquet_log.updateTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_log.updateUserId
     *
     * @return the value of t_banquet_log.updateUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getUpdateuserid() {
        return updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_log.updateUserId
     *
     * @param updateuserid the value for t_banquet_log.updateUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setUpdateuserid(String updateuserid) {
        this.updateuserid = updateuserid == null ? null : updateuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_log.updateUser
     *
     * @return the value of t_banquet_log.updateUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getUpdateuser() {
        return updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_log.updateUser
     *
     * @param updateuser the value for t_banquet_log.updateUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setUpdateuser(String updateuser) {
        this.updateuser = updateuser == null ? null : updateuser.trim();
    }
}