package com.jerry.banquet.model;

import java.util.Date;

public class TBanquetService {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_service.serviceId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String serviceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_service.banquetId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String banquetid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_service.name
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_service.departId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String departid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_service.departName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String departname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_service.timeNode
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Date timenode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_service.createTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_service.createUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String createuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_service.createUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String createuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_service.updateTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_service.updateUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String updateuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_service.updateUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String updateuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_service.serviceId
     *
     * @return the value of t_banquet_service.serviceId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getServiceid() {
        return serviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_service.serviceId
     *
     * @param serviceid the value for t_banquet_service.serviceId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setServiceid(String serviceid) {
        this.serviceid = serviceid == null ? null : serviceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_service.banquetId
     *
     * @return the value of t_banquet_service.banquetId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getBanquetid() {
        return banquetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_service.banquetId
     *
     * @param banquetid the value for t_banquet_service.banquetId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setBanquetid(String banquetid) {
        this.banquetid = banquetid == null ? null : banquetid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_service.name
     *
     * @return the value of t_banquet_service.name
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_service.name
     *
     * @param name the value for t_banquet_service.name
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_service.departId
     *
     * @return the value of t_banquet_service.departId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getDepartid() {
        return departid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_service.departId
     *
     * @param departid the value for t_banquet_service.departId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setDepartid(String departid) {
        this.departid = departid == null ? null : departid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_service.departName
     *
     * @return the value of t_banquet_service.departName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getDepartname() {
        return departname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_service.departName
     *
     * @param departname the value for t_banquet_service.departName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setDepartname(String departname) {
        this.departname = departname == null ? null : departname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_service.timeNode
     *
     * @return the value of t_banquet_service.timeNode
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Date getTimenode() {
        return timenode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_service.timeNode
     *
     * @param timenode the value for t_banquet_service.timeNode
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setTimenode(Date timenode) {
        this.timenode = timenode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_service.createTime
     *
     * @return the value of t_banquet_service.createTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_service.createTime
     *
     * @param createtime the value for t_banquet_service.createTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_service.createUserId
     *
     * @return the value of t_banquet_service.createUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_service.createUserId
     *
     * @param createuserid the value for t_banquet_service.createUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setCreateuserid(String createuserid) {
        this.createuserid = createuserid == null ? null : createuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_service.createUser
     *
     * @return the value of t_banquet_service.createUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_service.createUser
     *
     * @param createuser the value for t_banquet_service.createUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser == null ? null : createuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_service.updateTime
     *
     * @return the value of t_banquet_service.updateTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_service.updateTime
     *
     * @param updatetime the value for t_banquet_service.updateTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_service.updateUserId
     *
     * @return the value of t_banquet_service.updateUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getUpdateuserid() {
        return updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_service.updateUserId
     *
     * @param updateuserid the value for t_banquet_service.updateUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setUpdateuserid(String updateuserid) {
        this.updateuserid = updateuserid == null ? null : updateuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_service.updateUser
     *
     * @return the value of t_banquet_service.updateUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getUpdateuser() {
        return updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_service.updateUser
     *
     * @param updateuser the value for t_banquet_service.updateUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setUpdateuser(String updateuser) {
        this.updateuser = updateuser == null ? null : updateuser.trim();
    }
}