package com.jerry.banquet.model;

import java.util.Date;

public class TBanquetAffix {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_affix.affixId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String affixid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_affix.banquetId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String banquetid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_affix.originalFileName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String originalfilename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_affix.contractURL
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String contracturl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_affix.phType
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String phtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_affix.createTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_affix.createUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String createuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_affix.createUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String createuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_affix.updateTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_affix.updateUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String updateuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_affix.updateUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String updateuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_affix.affixId
     *
     * @return the value of t_banquet_affix.affixId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getAffixid() {
        return affixid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_affix.affixId
     *
     * @param affixid the value for t_banquet_affix.affixId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setAffixid(String affixid) {
        this.affixid = affixid == null ? null : affixid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_affix.banquetId
     *
     * @return the value of t_banquet_affix.banquetId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getBanquetid() {
        return banquetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_affix.banquetId
     *
     * @param banquetid the value for t_banquet_affix.banquetId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setBanquetid(String banquetid) {
        this.banquetid = banquetid == null ? null : banquetid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_affix.originalFileName
     *
     * @return the value of t_banquet_affix.originalFileName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getOriginalfilename() {
        return originalfilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_affix.originalFileName
     *
     * @param originalfilename the value for t_banquet_affix.originalFileName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setOriginalfilename(String originalfilename) {
        this.originalfilename = originalfilename == null ? null : originalfilename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_affix.contractURL
     *
     * @return the value of t_banquet_affix.contractURL
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getContracturl() {
        return contracturl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_affix.contractURL
     *
     * @param contracturl the value for t_banquet_affix.contractURL
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setContracturl(String contracturl) {
        this.contracturl = contracturl == null ? null : contracturl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_affix.phType
     *
     * @return the value of t_banquet_affix.phType
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getPhtype() {
        return phtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_affix.phType
     *
     * @param phtype the value for t_banquet_affix.phType
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setPhtype(String phtype) {
        this.phtype = phtype == null ? null : phtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_affix.createTime
     *
     * @return the value of t_banquet_affix.createTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_affix.createTime
     *
     * @param createtime the value for t_banquet_affix.createTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_affix.createUserId
     *
     * @return the value of t_banquet_affix.createUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_affix.createUserId
     *
     * @param createuserid the value for t_banquet_affix.createUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setCreateuserid(String createuserid) {
        this.createuserid = createuserid == null ? null : createuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_affix.createUser
     *
     * @return the value of t_banquet_affix.createUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_affix.createUser
     *
     * @param createuser the value for t_banquet_affix.createUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser == null ? null : createuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_affix.updateTime
     *
     * @return the value of t_banquet_affix.updateTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_affix.updateTime
     *
     * @param updatetime the value for t_banquet_affix.updateTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_affix.updateUserId
     *
     * @return the value of t_banquet_affix.updateUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getUpdateuserid() {
        return updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_affix.updateUserId
     *
     * @param updateuserid the value for t_banquet_affix.updateUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setUpdateuserid(String updateuserid) {
        this.updateuserid = updateuserid == null ? null : updateuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_affix.updateUser
     *
     * @return the value of t_banquet_affix.updateUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getUpdateuser() {
        return updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_affix.updateUser
     *
     * @param updateuser the value for t_banquet_affix.updateUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setUpdateuser(String updateuser) {
        this.updateuser = updateuser == null ? null : updateuser.trim();
    }
}