package com.jerry.banquet.model;

public class TBanquetOrderTemplateFields {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_order_template_fields.templateFiedId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String templatefiedid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_order_template_fields.templateId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String templateid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_order_template_fields.fieldKey
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String fieldkey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_order_template_fields.fieldValue
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String fieldvalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_order_template_fields.fieldValueEnd
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String fieldvalueend;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_order_template_fields.templateFiedId
     *
     * @return the value of t_banquet_order_template_fields.templateFiedId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getTemplatefiedid() {
        return templatefiedid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_order_template_fields.templateFiedId
     *
     * @param templatefiedid the value for t_banquet_order_template_fields.templateFiedId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setTemplatefiedid(String templatefiedid) {
        this.templatefiedid = templatefiedid == null ? null : templatefiedid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_order_template_fields.templateId
     *
     * @return the value of t_banquet_order_template_fields.templateId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getTemplateid() {
        return templateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_order_template_fields.templateId
     *
     * @param templateid the value for t_banquet_order_template_fields.templateId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setTemplateid(String templateid) {
        this.templateid = templateid == null ? null : templateid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_order_template_fields.fieldKey
     *
     * @return the value of t_banquet_order_template_fields.fieldKey
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getFieldkey() {
        return fieldkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_order_template_fields.fieldKey
     *
     * @param fieldkey the value for t_banquet_order_template_fields.fieldKey
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setFieldkey(String fieldkey) {
        this.fieldkey = fieldkey == null ? null : fieldkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_order_template_fields.fieldValue
     *
     * @return the value of t_banquet_order_template_fields.fieldValue
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getFieldvalue() {
        return fieldvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_order_template_fields.fieldValue
     *
     * @param fieldvalue the value for t_banquet_order_template_fields.fieldValue
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setFieldvalue(String fieldvalue) {
        this.fieldvalue = fieldvalue == null ? null : fieldvalue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_order_template_fields.fieldValueEnd
     *
     * @return the value of t_banquet_order_template_fields.fieldValueEnd
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getFieldvalueend() {
        return fieldvalueend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_order_template_fields.fieldValueEnd
     *
     * @param fieldvalueend the value for t_banquet_order_template_fields.fieldValueEnd
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setFieldvalueend(String fieldvalueend) {
        this.fieldvalueend = fieldvalueend == null ? null : fieldvalueend.trim();
    }
}