package com.jerry.banquet.model;

import java.util.Date;

public class TBanquetMemorandum {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_memorandum.memorandumId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String memorandumid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_memorandum.banquetId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String banquetid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_memorandum.noteTakerId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String notetakerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_memorandum.noteTakerName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String notetakername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_memorandum.noteDate
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Date notedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_memorandum.content
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_memorandum.createTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_memorandum.createUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String createuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_memorandum.createUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String createuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_memorandum.updateTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_memorandum.updateUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String updateuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_memorandum.updateUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String updateuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_memorandum.memorandumId
     *
     * @return the value of t_banquet_memorandum.memorandumId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getMemorandumid() {
        return memorandumid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_memorandum.memorandumId
     *
     * @param memorandumid the value for t_banquet_memorandum.memorandumId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setMemorandumid(String memorandumid) {
        this.memorandumid = memorandumid == null ? null : memorandumid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_memorandum.banquetId
     *
     * @return the value of t_banquet_memorandum.banquetId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getBanquetid() {
        return banquetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_memorandum.banquetId
     *
     * @param banquetid the value for t_banquet_memorandum.banquetId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setBanquetid(String banquetid) {
        this.banquetid = banquetid == null ? null : banquetid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_memorandum.noteTakerId
     *
     * @return the value of t_banquet_memorandum.noteTakerId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getNotetakerid() {
        return notetakerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_memorandum.noteTakerId
     *
     * @param notetakerid the value for t_banquet_memorandum.noteTakerId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setNotetakerid(String notetakerid) {
        this.notetakerid = notetakerid == null ? null : notetakerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_memorandum.noteTakerName
     *
     * @return the value of t_banquet_memorandum.noteTakerName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getNotetakername() {
        return notetakername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_memorandum.noteTakerName
     *
     * @param notetakername the value for t_banquet_memorandum.noteTakerName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setNotetakername(String notetakername) {
        this.notetakername = notetakername == null ? null : notetakername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_memorandum.noteDate
     *
     * @return the value of t_banquet_memorandum.noteDate
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Date getNotedate() {
        return notedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_memorandum.noteDate
     *
     * @param notedate the value for t_banquet_memorandum.noteDate
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setNotedate(Date notedate) {
        this.notedate = notedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_memorandum.content
     *
     * @return the value of t_banquet_memorandum.content
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_memorandum.content
     *
     * @param content the value for t_banquet_memorandum.content
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_memorandum.createTime
     *
     * @return the value of t_banquet_memorandum.createTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_memorandum.createTime
     *
     * @param createtime the value for t_banquet_memorandum.createTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_memorandum.createUserId
     *
     * @return the value of t_banquet_memorandum.createUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_memorandum.createUserId
     *
     * @param createuserid the value for t_banquet_memorandum.createUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setCreateuserid(String createuserid) {
        this.createuserid = createuserid == null ? null : createuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_memorandum.createUser
     *
     * @return the value of t_banquet_memorandum.createUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_memorandum.createUser
     *
     * @param createuser the value for t_banquet_memorandum.createUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser == null ? null : createuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_memorandum.updateTime
     *
     * @return the value of t_banquet_memorandum.updateTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_memorandum.updateTime
     *
     * @param updatetime the value for t_banquet_memorandum.updateTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_memorandum.updateUserId
     *
     * @return the value of t_banquet_memorandum.updateUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getUpdateuserid() {
        return updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_memorandum.updateUserId
     *
     * @param updateuserid the value for t_banquet_memorandum.updateUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setUpdateuserid(String updateuserid) {
        this.updateuserid = updateuserid == null ? null : updateuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_memorandum.updateUser
     *
     * @return the value of t_banquet_memorandum.updateUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getUpdateuser() {
        return updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_memorandum.updateUser
     *
     * @param updateuser the value for t_banquet_memorandum.updateUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setUpdateuser(String updateuser) {
        this.updateuser = updateuser == null ? null : updateuser.trim();
    }
}