package com.jerry.banquet.model;

public class TBanquetOrderField {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_order_field.fieldId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String fieldid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_order_field.orderStage
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Integer orderstage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_order_field.fieldKey
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String fieldkey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_order_field.fieldName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String fieldname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_order_field.fieldType
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Integer fieldtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_order_field.tableName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String tablename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_order_field.tableSelectKey
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String tableselectkey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_order_field.tableSelectValue
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String tableselectvalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_order_field.isValid
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Integer isvalid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_order_field.orderPostion
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Integer orderpostion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_order_field.fieldId
     *
     * @return the value of t_banquet_order_field.fieldId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getFieldid() {
        return fieldid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_order_field.fieldId
     *
     * @param fieldid the value for t_banquet_order_field.fieldId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setFieldid(String fieldid) {
        this.fieldid = fieldid == null ? null : fieldid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_order_field.orderStage
     *
     * @return the value of t_banquet_order_field.orderStage
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Integer getOrderstage() {
        return orderstage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_order_field.orderStage
     *
     * @param orderstage the value for t_banquet_order_field.orderStage
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setOrderstage(Integer orderstage) {
        this.orderstage = orderstage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_order_field.fieldKey
     *
     * @return the value of t_banquet_order_field.fieldKey
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getFieldkey() {
        return fieldkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_order_field.fieldKey
     *
     * @param fieldkey the value for t_banquet_order_field.fieldKey
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setFieldkey(String fieldkey) {
        this.fieldkey = fieldkey == null ? null : fieldkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_order_field.fieldName
     *
     * @return the value of t_banquet_order_field.fieldName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getFieldname() {
        return fieldname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_order_field.fieldName
     *
     * @param fieldname the value for t_banquet_order_field.fieldName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setFieldname(String fieldname) {
        this.fieldname = fieldname == null ? null : fieldname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_order_field.fieldType
     *
     * @return the value of t_banquet_order_field.fieldType
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Integer getFieldtype() {
        return fieldtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_order_field.fieldType
     *
     * @param fieldtype the value for t_banquet_order_field.fieldType
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setFieldtype(Integer fieldtype) {
        this.fieldtype = fieldtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_order_field.tableName
     *
     * @return the value of t_banquet_order_field.tableName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getTablename() {
        return tablename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_order_field.tableName
     *
     * @param tablename the value for t_banquet_order_field.tableName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setTablename(String tablename) {
        this.tablename = tablename == null ? null : tablename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_order_field.tableSelectKey
     *
     * @return the value of t_banquet_order_field.tableSelectKey
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getTableselectkey() {
        return tableselectkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_order_field.tableSelectKey
     *
     * @param tableselectkey the value for t_banquet_order_field.tableSelectKey
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setTableselectkey(String tableselectkey) {
        this.tableselectkey = tableselectkey == null ? null : tableselectkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_order_field.tableSelectValue
     *
     * @return the value of t_banquet_order_field.tableSelectValue
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getTableselectvalue() {
        return tableselectvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_order_field.tableSelectValue
     *
     * @param tableselectvalue the value for t_banquet_order_field.tableSelectValue
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setTableselectvalue(String tableselectvalue) {
        this.tableselectvalue = tableselectvalue == null ? null : tableselectvalue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_order_field.isValid
     *
     * @return the value of t_banquet_order_field.isValid
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Integer getIsvalid() {
        return isvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_order_field.isValid
     *
     * @param isvalid the value for t_banquet_order_field.isValid
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setIsvalid(Integer isvalid) {
        this.isvalid = isvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_order_field.orderPostion
     *
     * @return the value of t_banquet_order_field.orderPostion
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Integer getOrderpostion() {
        return orderpostion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_order_field.orderPostion
     *
     * @param orderpostion the value for t_banquet_order_field.orderPostion
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setOrderpostion(Integer orderpostion) {
        this.orderpostion = orderpostion;
    }
}