package com.jerry.banquet.model;

import java.util.Date;

public class TBanquetTimesheet {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_timesheet.timesheetId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String timesheetid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_timesheet.banquetId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String banquetid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_timesheet.name
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_timesheet.timeNode
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Date timenode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_timesheet.createTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_timesheet.createUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String createuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_timesheet.createUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String createuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_timesheet.updateTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_timesheet.updateUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String updateuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_timesheet.updateUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String updateuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_timesheet.timesheetId
     *
     * @return the value of t_banquet_timesheet.timesheetId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getTimesheetid() {
        return timesheetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_timesheet.timesheetId
     *
     * @param timesheetid the value for t_banquet_timesheet.timesheetId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setTimesheetid(String timesheetid) {
        this.timesheetid = timesheetid == null ? null : timesheetid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_timesheet.banquetId
     *
     * @return the value of t_banquet_timesheet.banquetId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getBanquetid() {
        return banquetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_timesheet.banquetId
     *
     * @param banquetid the value for t_banquet_timesheet.banquetId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setBanquetid(String banquetid) {
        this.banquetid = banquetid == null ? null : banquetid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_timesheet.name
     *
     * @return the value of t_banquet_timesheet.name
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_timesheet.name
     *
     * @param name the value for t_banquet_timesheet.name
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_timesheet.timeNode
     *
     * @return the value of t_banquet_timesheet.timeNode
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Date getTimenode() {
        return timenode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_timesheet.timeNode
     *
     * @param timenode the value for t_banquet_timesheet.timeNode
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setTimenode(Date timenode) {
        this.timenode = timenode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_timesheet.createTime
     *
     * @return the value of t_banquet_timesheet.createTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_timesheet.createTime
     *
     * @param createtime the value for t_banquet_timesheet.createTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_timesheet.createUserId
     *
     * @return the value of t_banquet_timesheet.createUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_timesheet.createUserId
     *
     * @param createuserid the value for t_banquet_timesheet.createUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setCreateuserid(String createuserid) {
        this.createuserid = createuserid == null ? null : createuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_timesheet.createUser
     *
     * @return the value of t_banquet_timesheet.createUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_timesheet.createUser
     *
     * @param createuser the value for t_banquet_timesheet.createUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser == null ? null : createuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_timesheet.updateTime
     *
     * @return the value of t_banquet_timesheet.updateTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_timesheet.updateTime
     *
     * @param updatetime the value for t_banquet_timesheet.updateTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_timesheet.updateUserId
     *
     * @return the value of t_banquet_timesheet.updateUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getUpdateuserid() {
        return updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_timesheet.updateUserId
     *
     * @param updateuserid the value for t_banquet_timesheet.updateUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setUpdateuserid(String updateuserid) {
        this.updateuserid = updateuserid == null ? null : updateuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_timesheet.updateUser
     *
     * @return the value of t_banquet_timesheet.updateUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getUpdateuser() {
        return updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_timesheet.updateUser
     *
     * @param updateuser the value for t_banquet_timesheet.updateUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setUpdateuser(String updateuser) {
        this.updateuser = updateuser == null ? null : updateuser.trim();
    }
}