package com.jerry.banquet.model;

import java.util.Date;

public class TBanquetFacility {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_facility.banquetFacilityId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String banquetfacilityid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_facility.facilityId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String facilityid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_facility.banquetId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String banquetid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_facility.facilityName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String facilityname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_facility.price
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_facility.number
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_facility.responDepartId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String respondepartid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_facility.responDepartName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String respondepartname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_facility.negotPrice
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Integer negotprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_facility.negotiable
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Integer negotiable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_facility.createTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_facility.createUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String createuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_facility.createUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String createuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_facility.updateTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_facility.updateUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String updateuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_facility.updateUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String updateuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_facility.banquetFacilityId
     *
     * @return the value of t_banquet_facility.banquetFacilityId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getBanquetfacilityid() {
        return banquetfacilityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_facility.banquetFacilityId
     *
     * @param banquetfacilityid the value for t_banquet_facility.banquetFacilityId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setBanquetfacilityid(String banquetfacilityid) {
        this.banquetfacilityid = banquetfacilityid == null ? null : banquetfacilityid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_facility.facilityId
     *
     * @return the value of t_banquet_facility.facilityId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getFacilityid() {
        return facilityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_facility.facilityId
     *
     * @param facilityid the value for t_banquet_facility.facilityId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setFacilityid(String facilityid) {
        this.facilityid = facilityid == null ? null : facilityid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_facility.banquetId
     *
     * @return the value of t_banquet_facility.banquetId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getBanquetid() {
        return banquetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_facility.banquetId
     *
     * @param banquetid the value for t_banquet_facility.banquetId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setBanquetid(String banquetid) {
        this.banquetid = banquetid == null ? null : banquetid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_facility.facilityName
     *
     * @return the value of t_banquet_facility.facilityName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getFacilityname() {
        return facilityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_facility.facilityName
     *
     * @param facilityname the value for t_banquet_facility.facilityName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setFacilityname(String facilityname) {
        this.facilityname = facilityname == null ? null : facilityname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_facility.price
     *
     * @return the value of t_banquet_facility.price
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_facility.price
     *
     * @param price the value for t_banquet_facility.price
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_facility.number
     *
     * @return the value of t_banquet_facility.number
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_facility.number
     *
     * @param number the value for t_banquet_facility.number
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_facility.responDepartId
     *
     * @return the value of t_banquet_facility.responDepartId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getRespondepartid() {
        return respondepartid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_facility.responDepartId
     *
     * @param respondepartid the value for t_banquet_facility.responDepartId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setRespondepartid(String respondepartid) {
        this.respondepartid = respondepartid == null ? null : respondepartid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_facility.responDepartName
     *
     * @return the value of t_banquet_facility.responDepartName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getRespondepartname() {
        return respondepartname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_facility.responDepartName
     *
     * @param respondepartname the value for t_banquet_facility.responDepartName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setRespondepartname(String respondepartname) {
        this.respondepartname = respondepartname == null ? null : respondepartname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_facility.negotPrice
     *
     * @return the value of t_banquet_facility.negotPrice
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Integer getNegotprice() {
        return negotprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_facility.negotPrice
     *
     * @param negotprice the value for t_banquet_facility.negotPrice
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setNegotprice(Integer negotprice) {
        this.negotprice = negotprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_facility.negotiable
     *
     * @return the value of t_banquet_facility.negotiable
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Integer getNegotiable() {
        return negotiable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_facility.negotiable
     *
     * @param negotiable the value for t_banquet_facility.negotiable
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setNegotiable(Integer negotiable) {
        this.negotiable = negotiable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_facility.createTime
     *
     * @return the value of t_banquet_facility.createTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_facility.createTime
     *
     * @param createtime the value for t_banquet_facility.createTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_facility.createUserId
     *
     * @return the value of t_banquet_facility.createUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_facility.createUserId
     *
     * @param createuserid the value for t_banquet_facility.createUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setCreateuserid(String createuserid) {
        this.createuserid = createuserid == null ? null : createuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_facility.createUser
     *
     * @return the value of t_banquet_facility.createUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_facility.createUser
     *
     * @param createuser the value for t_banquet_facility.createUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser == null ? null : createuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_facility.updateTime
     *
     * @return the value of t_banquet_facility.updateTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_facility.updateTime
     *
     * @param updatetime the value for t_banquet_facility.updateTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_facility.updateUserId
     *
     * @return the value of t_banquet_facility.updateUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getUpdateuserid() {
        return updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_facility.updateUserId
     *
     * @param updateuserid the value for t_banquet_facility.updateUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setUpdateuserid(String updateuserid) {
        this.updateuserid = updateuserid == null ? null : updateuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_facility.updateUser
     *
     * @return the value of t_banquet_facility.updateUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getUpdateuser() {
        return updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_facility.updateUser
     *
     * @param updateuser the value for t_banquet_facility.updateUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setUpdateuser(String updateuser) {
        this.updateuser = updateuser == null ? null : updateuser.trim();
    }
}