package com.jerry.banquet.model;

import java.util.Date;

public class TBanquetDepositDetails {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_deposit_details.detailsId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String detailsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_deposit_details.banquetId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String banquetid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_deposit_details.amount
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_deposit_details.payType
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String paytype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_deposit_details.receiptId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String receiptid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_deposit_details.payTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Date paytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_deposit_details.payee
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String payee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_deposit_details.payeeId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String payeeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_deposit_details.drawee
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String drawee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_deposit_details.draweeId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String draweeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_deposit_details.depositType
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String deposittype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_deposit_details.createTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_deposit_details.createUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String createuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_deposit_details.createUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String createuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_deposit_details.updateTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_deposit_details.updateUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String updateuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_deposit_details.updateUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String updateuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_deposit_details.detailsId
     *
     * @return the value of t_banquet_deposit_details.detailsId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getDetailsid() {
        return detailsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_deposit_details.detailsId
     *
     * @param detailsid the value for t_banquet_deposit_details.detailsId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setDetailsid(String detailsid) {
        this.detailsid = detailsid == null ? null : detailsid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_deposit_details.banquetId
     *
     * @return the value of t_banquet_deposit_details.banquetId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getBanquetid() {
        return banquetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_deposit_details.banquetId
     *
     * @param banquetid the value for t_banquet_deposit_details.banquetId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setBanquetid(String banquetid) {
        this.banquetid = banquetid == null ? null : banquetid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_deposit_details.amount
     *
     * @return the value of t_banquet_deposit_details.amount
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_deposit_details.amount
     *
     * @param amount the value for t_banquet_deposit_details.amount
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_deposit_details.payType
     *
     * @return the value of t_banquet_deposit_details.payType
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getPaytype() {
        return paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_deposit_details.payType
     *
     * @param paytype the value for t_banquet_deposit_details.payType
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setPaytype(String paytype) {
        this.paytype = paytype == null ? null : paytype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_deposit_details.receiptId
     *
     * @return the value of t_banquet_deposit_details.receiptId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getReceiptid() {
        return receiptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_deposit_details.receiptId
     *
     * @param receiptid the value for t_banquet_deposit_details.receiptId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setReceiptid(String receiptid) {
        this.receiptid = receiptid == null ? null : receiptid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_deposit_details.payTime
     *
     * @return the value of t_banquet_deposit_details.payTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Date getPaytime() {
        return paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_deposit_details.payTime
     *
     * @param paytime the value for t_banquet_deposit_details.payTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setPaytime(Date paytime) {
        this.paytime = paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_deposit_details.payee
     *
     * @return the value of t_banquet_deposit_details.payee
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getPayee() {
        return payee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_deposit_details.payee
     *
     * @param payee the value for t_banquet_deposit_details.payee
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setPayee(String payee) {
        this.payee = payee == null ? null : payee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_deposit_details.payeeId
     *
     * @return the value of t_banquet_deposit_details.payeeId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getPayeeid() {
        return payeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_deposit_details.payeeId
     *
     * @param payeeid the value for t_banquet_deposit_details.payeeId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setPayeeid(String payeeid) {
        this.payeeid = payeeid == null ? null : payeeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_deposit_details.drawee
     *
     * @return the value of t_banquet_deposit_details.drawee
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getDrawee() {
        return drawee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_deposit_details.drawee
     *
     * @param drawee the value for t_banquet_deposit_details.drawee
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setDrawee(String drawee) {
        this.drawee = drawee == null ? null : drawee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_deposit_details.draweeId
     *
     * @return the value of t_banquet_deposit_details.draweeId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getDraweeid() {
        return draweeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_deposit_details.draweeId
     *
     * @param draweeid the value for t_banquet_deposit_details.draweeId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setDraweeid(String draweeid) {
        this.draweeid = draweeid == null ? null : draweeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_deposit_details.depositType
     *
     * @return the value of t_banquet_deposit_details.depositType
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getDeposittype() {
        return deposittype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_deposit_details.depositType
     *
     * @param deposittype the value for t_banquet_deposit_details.depositType
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setDeposittype(String deposittype) {
        this.deposittype = deposittype == null ? null : deposittype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_deposit_details.createTime
     *
     * @return the value of t_banquet_deposit_details.createTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_deposit_details.createTime
     *
     * @param createtime the value for t_banquet_deposit_details.createTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_deposit_details.createUserId
     *
     * @return the value of t_banquet_deposit_details.createUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_deposit_details.createUserId
     *
     * @param createuserid the value for t_banquet_deposit_details.createUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setCreateuserid(String createuserid) {
        this.createuserid = createuserid == null ? null : createuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_deposit_details.createUser
     *
     * @return the value of t_banquet_deposit_details.createUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_deposit_details.createUser
     *
     * @param createuser the value for t_banquet_deposit_details.createUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser == null ? null : createuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_deposit_details.updateTime
     *
     * @return the value of t_banquet_deposit_details.updateTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_deposit_details.updateTime
     *
     * @param updatetime the value for t_banquet_deposit_details.updateTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_deposit_details.updateUserId
     *
     * @return the value of t_banquet_deposit_details.updateUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getUpdateuserid() {
        return updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_deposit_details.updateUserId
     *
     * @param updateuserid the value for t_banquet_deposit_details.updateUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setUpdateuserid(String updateuserid) {
        this.updateuserid = updateuserid == null ? null : updateuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_deposit_details.updateUser
     *
     * @return the value of t_banquet_deposit_details.updateUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getUpdateuser() {
        return updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_deposit_details.updateUser
     *
     * @param updateuser the value for t_banquet_deposit_details.updateUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setUpdateuser(String updateuser) {
        this.updateuser = updateuser == null ? null : updateuser.trim();
    }
}