package com.jerry.banquet.model;

import java.util.Date;

public class TBanquetContract {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_contract.banquetId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String banquetid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_contract.finishReDeposit
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String finishredeposit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_contract.breakReDeposit
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String breakredeposit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_contract.reDepositAmount
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Integer redepositamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_contract.depositRemark
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String depositremark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_contract.paymentMethod
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String paymentmethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_contract.settlementMethod
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String settlementmethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_contract.settlePeriod
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Integer settleperiod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_contract.firstPayment
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Integer firstpayment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_contract.firstPaymentDate
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Date firstpaymentdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_contract.finalPayment
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Integer finalpayment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_contract.finalPaymentDate
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Date finalpaymentdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_contract.guarantor
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String guarantor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_contract.guaranteExplain
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String guaranteexplain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_contract.custsigner
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String custsigner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_contract.shopSigner
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String shopsigner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_contract.contractNumber
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String contractnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_contract.invoiceType
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String invoicetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_contract.invoiceAmount
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Integer invoiceamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_contract.invoicePayee
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String invoicepayee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_contract.invoicePayeeTel
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String invoicepayeetel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_contract.payeeAddress
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String payeeaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_contract.zipCode
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String zipcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_contract.company
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String company;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_contract.taxpayerNum
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String taxpayernum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_contract.registerAddress
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String registeraddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_contract.registerTel
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String registertel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_contract.openingBank
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String openingbank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_contract.accountNumber
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String accountnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_contract.createTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_contract.createUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String createuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_contract.createUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String createuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_contract.updateTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_contract.updateUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String updateuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_contract.updateUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String updateuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_contract.banquetId
     *
     * @return the value of t_banquet_contract.banquetId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getBanquetid() {
        return banquetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_contract.banquetId
     *
     * @param banquetid the value for t_banquet_contract.banquetId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setBanquetid(String banquetid) {
        this.banquetid = banquetid == null ? null : banquetid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_contract.finishReDeposit
     *
     * @return the value of t_banquet_contract.finishReDeposit
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getFinishredeposit() {
        return finishredeposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_contract.finishReDeposit
     *
     * @param finishredeposit the value for t_banquet_contract.finishReDeposit
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setFinishredeposit(String finishredeposit) {
        this.finishredeposit = finishredeposit == null ? null : finishredeposit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_contract.breakReDeposit
     *
     * @return the value of t_banquet_contract.breakReDeposit
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getBreakredeposit() {
        return breakredeposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_contract.breakReDeposit
     *
     * @param breakredeposit the value for t_banquet_contract.breakReDeposit
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setBreakredeposit(String breakredeposit) {
        this.breakredeposit = breakredeposit == null ? null : breakredeposit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_contract.reDepositAmount
     *
     * @return the value of t_banquet_contract.reDepositAmount
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Integer getRedepositamount() {
        return redepositamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_contract.reDepositAmount
     *
     * @param redepositamount the value for t_banquet_contract.reDepositAmount
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setRedepositamount(Integer redepositamount) {
        this.redepositamount = redepositamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_contract.depositRemark
     *
     * @return the value of t_banquet_contract.depositRemark
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getDepositremark() {
        return depositremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_contract.depositRemark
     *
     * @param depositremark the value for t_banquet_contract.depositRemark
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setDepositremark(String depositremark) {
        this.depositremark = depositremark == null ? null : depositremark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_contract.paymentMethod
     *
     * @return the value of t_banquet_contract.paymentMethod
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getPaymentmethod() {
        return paymentmethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_contract.paymentMethod
     *
     * @param paymentmethod the value for t_banquet_contract.paymentMethod
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setPaymentmethod(String paymentmethod) {
        this.paymentmethod = paymentmethod == null ? null : paymentmethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_contract.settlementMethod
     *
     * @return the value of t_banquet_contract.settlementMethod
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getSettlementmethod() {
        return settlementmethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_contract.settlementMethod
     *
     * @param settlementmethod the value for t_banquet_contract.settlementMethod
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setSettlementmethod(String settlementmethod) {
        this.settlementmethod = settlementmethod == null ? null : settlementmethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_contract.settlePeriod
     *
     * @return the value of t_banquet_contract.settlePeriod
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Integer getSettleperiod() {
        return settleperiod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_contract.settlePeriod
     *
     * @param settleperiod the value for t_banquet_contract.settlePeriod
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setSettleperiod(Integer settleperiod) {
        this.settleperiod = settleperiod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_contract.firstPayment
     *
     * @return the value of t_banquet_contract.firstPayment
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Integer getFirstpayment() {
        return firstpayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_contract.firstPayment
     *
     * @param firstpayment the value for t_banquet_contract.firstPayment
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setFirstpayment(Integer firstpayment) {
        this.firstpayment = firstpayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_contract.firstPaymentDate
     *
     * @return the value of t_banquet_contract.firstPaymentDate
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Date getFirstpaymentdate() {
        return firstpaymentdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_contract.firstPaymentDate
     *
     * @param firstpaymentdate the value for t_banquet_contract.firstPaymentDate
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setFirstpaymentdate(Date firstpaymentdate) {
        this.firstpaymentdate = firstpaymentdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_contract.finalPayment
     *
     * @return the value of t_banquet_contract.finalPayment
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Integer getFinalpayment() {
        return finalpayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_contract.finalPayment
     *
     * @param finalpayment the value for t_banquet_contract.finalPayment
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setFinalpayment(Integer finalpayment) {
        this.finalpayment = finalpayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_contract.finalPaymentDate
     *
     * @return the value of t_banquet_contract.finalPaymentDate
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Date getFinalpaymentdate() {
        return finalpaymentdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_contract.finalPaymentDate
     *
     * @param finalpaymentdate the value for t_banquet_contract.finalPaymentDate
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setFinalpaymentdate(Date finalpaymentdate) {
        this.finalpaymentdate = finalpaymentdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_contract.guarantor
     *
     * @return the value of t_banquet_contract.guarantor
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getGuarantor() {
        return guarantor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_contract.guarantor
     *
     * @param guarantor the value for t_banquet_contract.guarantor
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setGuarantor(String guarantor) {
        this.guarantor = guarantor == null ? null : guarantor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_contract.guaranteExplain
     *
     * @return the value of t_banquet_contract.guaranteExplain
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getGuaranteexplain() {
        return guaranteexplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_contract.guaranteExplain
     *
     * @param guaranteexplain the value for t_banquet_contract.guaranteExplain
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setGuaranteexplain(String guaranteexplain) {
        this.guaranteexplain = guaranteexplain == null ? null : guaranteexplain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_contract.custsigner
     *
     * @return the value of t_banquet_contract.custsigner
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getCustsigner() {
        return custsigner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_contract.custsigner
     *
     * @param custsigner the value for t_banquet_contract.custsigner
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setCustsigner(String custsigner) {
        this.custsigner = custsigner == null ? null : custsigner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_contract.shopSigner
     *
     * @return the value of t_banquet_contract.shopSigner
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getShopsigner() {
        return shopsigner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_contract.shopSigner
     *
     * @param shopsigner the value for t_banquet_contract.shopSigner
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setShopsigner(String shopsigner) {
        this.shopsigner = shopsigner == null ? null : shopsigner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_contract.contractNumber
     *
     * @return the value of t_banquet_contract.contractNumber
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getContractnumber() {
        return contractnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_contract.contractNumber
     *
     * @param contractnumber the value for t_banquet_contract.contractNumber
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setContractnumber(String contractnumber) {
        this.contractnumber = contractnumber == null ? null : contractnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_contract.invoiceType
     *
     * @return the value of t_banquet_contract.invoiceType
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getInvoicetype() {
        return invoicetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_contract.invoiceType
     *
     * @param invoicetype the value for t_banquet_contract.invoiceType
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setInvoicetype(String invoicetype) {
        this.invoicetype = invoicetype == null ? null : invoicetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_contract.invoiceAmount
     *
     * @return the value of t_banquet_contract.invoiceAmount
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Integer getInvoiceamount() {
        return invoiceamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_contract.invoiceAmount
     *
     * @param invoiceamount the value for t_banquet_contract.invoiceAmount
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setInvoiceamount(Integer invoiceamount) {
        this.invoiceamount = invoiceamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_contract.invoicePayee
     *
     * @return the value of t_banquet_contract.invoicePayee
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getInvoicepayee() {
        return invoicepayee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_contract.invoicePayee
     *
     * @param invoicepayee the value for t_banquet_contract.invoicePayee
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setInvoicepayee(String invoicepayee) {
        this.invoicepayee = invoicepayee == null ? null : invoicepayee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_contract.invoicePayeeTel
     *
     * @return the value of t_banquet_contract.invoicePayeeTel
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getInvoicepayeetel() {
        return invoicepayeetel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_contract.invoicePayeeTel
     *
     * @param invoicepayeetel the value for t_banquet_contract.invoicePayeeTel
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setInvoicepayeetel(String invoicepayeetel) {
        this.invoicepayeetel = invoicepayeetel == null ? null : invoicepayeetel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_contract.payeeAddress
     *
     * @return the value of t_banquet_contract.payeeAddress
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getPayeeaddress() {
        return payeeaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_contract.payeeAddress
     *
     * @param payeeaddress the value for t_banquet_contract.payeeAddress
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setPayeeaddress(String payeeaddress) {
        this.payeeaddress = payeeaddress == null ? null : payeeaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_contract.zipCode
     *
     * @return the value of t_banquet_contract.zipCode
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getZipcode() {
        return zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_contract.zipCode
     *
     * @param zipcode the value for t_banquet_contract.zipCode
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode == null ? null : zipcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_contract.company
     *
     * @return the value of t_banquet_contract.company
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_contract.company
     *
     * @param company the value for t_banquet_contract.company
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_contract.taxpayerNum
     *
     * @return the value of t_banquet_contract.taxpayerNum
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getTaxpayernum() {
        return taxpayernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_contract.taxpayerNum
     *
     * @param taxpayernum the value for t_banquet_contract.taxpayerNum
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setTaxpayernum(String taxpayernum) {
        this.taxpayernum = taxpayernum == null ? null : taxpayernum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_contract.registerAddress
     *
     * @return the value of t_banquet_contract.registerAddress
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getRegisteraddress() {
        return registeraddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_contract.registerAddress
     *
     * @param registeraddress the value for t_banquet_contract.registerAddress
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setRegisteraddress(String registeraddress) {
        this.registeraddress = registeraddress == null ? null : registeraddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_contract.registerTel
     *
     * @return the value of t_banquet_contract.registerTel
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getRegistertel() {
        return registertel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_contract.registerTel
     *
     * @param registertel the value for t_banquet_contract.registerTel
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setRegistertel(String registertel) {
        this.registertel = registertel == null ? null : registertel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_contract.openingBank
     *
     * @return the value of t_banquet_contract.openingBank
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getOpeningbank() {
        return openingbank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_contract.openingBank
     *
     * @param openingbank the value for t_banquet_contract.openingBank
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setOpeningbank(String openingbank) {
        this.openingbank = openingbank == null ? null : openingbank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_contract.accountNumber
     *
     * @return the value of t_banquet_contract.accountNumber
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getAccountnumber() {
        return accountnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_contract.accountNumber
     *
     * @param accountnumber the value for t_banquet_contract.accountNumber
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setAccountnumber(String accountnumber) {
        this.accountnumber = accountnumber == null ? null : accountnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_contract.createTime
     *
     * @return the value of t_banquet_contract.createTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_contract.createTime
     *
     * @param createtime the value for t_banquet_contract.createTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_contract.createUserId
     *
     * @return the value of t_banquet_contract.createUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_contract.createUserId
     *
     * @param createuserid the value for t_banquet_contract.createUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setCreateuserid(String createuserid) {
        this.createuserid = createuserid == null ? null : createuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_contract.createUser
     *
     * @return the value of t_banquet_contract.createUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_contract.createUser
     *
     * @param createuser the value for t_banquet_contract.createUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser == null ? null : createuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_contract.updateTime
     *
     * @return the value of t_banquet_contract.updateTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_contract.updateTime
     *
     * @param updatetime the value for t_banquet_contract.updateTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_contract.updateUserId
     *
     * @return the value of t_banquet_contract.updateUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getUpdateuserid() {
        return updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_contract.updateUserId
     *
     * @param updateuserid the value for t_banquet_contract.updateUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setUpdateuserid(String updateuserid) {
        this.updateuserid = updateuserid == null ? null : updateuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_contract.updateUser
     *
     * @return the value of t_banquet_contract.updateUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getUpdateuser() {
        return updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_contract.updateUser
     *
     * @param updateuser the value for t_banquet_contract.updateUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setUpdateuser(String updateuser) {
        this.updateuser = updateuser == null ? null : updateuser.trim();
    }
}