package com.jerry.banquet.model;

import java.util.Date;

public class TBanquetPhase {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_phase.phaseId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String phaseid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_phase.banquetId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String banquetid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_phase.nicheCreateTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Date nichecreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_phase.nicheStartTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Date nichestarttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_phase.nicheEndTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Date nicheendtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_phase.nicheCycleDay
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Integer nichecycleday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_phase.intentCreateTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Date intentcreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_phase.intentStartTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Date intentstarttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_phase.intentEndTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Date intentendtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_phase.intentCycleDay
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Integer intentcycleday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_phase.priceCreateTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Date pricecreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_phase.priceStartTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Date pricestarttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_phase.priceEndTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Date priceendtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_phase.priceCycleDay
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Integer pricecycleday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_phase.contractCreateTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Date contractcreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_phase.contractStartTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Date contractstarttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_phase.contractEndTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Date contractendtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_phase.contractCycleDay
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Integer contractcycleday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_phase.prepareCreateTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Date preparecreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_phase.prepareStartTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Date preparestarttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_phase.prepareEndTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Date prepareendtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_phase.prepareCycleDay
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Integer preparecycleday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_phase.createTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_phase.createUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String createuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_phase.createUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String createuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_phase.updateTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_phase.updateUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String updateuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_phase.updateUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String updateuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_phase.phaseId
     *
     * @return the value of t_banquet_phase.phaseId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getPhaseid() {
        return phaseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_phase.phaseId
     *
     * @param phaseid the value for t_banquet_phase.phaseId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setPhaseid(String phaseid) {
        this.phaseid = phaseid == null ? null : phaseid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_phase.banquetId
     *
     * @return the value of t_banquet_phase.banquetId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getBanquetid() {
        return banquetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_phase.banquetId
     *
     * @param banquetid the value for t_banquet_phase.banquetId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setBanquetid(String banquetid) {
        this.banquetid = banquetid == null ? null : banquetid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_phase.nicheCreateTime
     *
     * @return the value of t_banquet_phase.nicheCreateTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Date getNichecreatetime() {
        return nichecreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_phase.nicheCreateTime
     *
     * @param nichecreatetime the value for t_banquet_phase.nicheCreateTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setNichecreatetime(Date nichecreatetime) {
        this.nichecreatetime = nichecreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_phase.nicheStartTime
     *
     * @return the value of t_banquet_phase.nicheStartTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Date getNichestarttime() {
        return nichestarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_phase.nicheStartTime
     *
     * @param nichestarttime the value for t_banquet_phase.nicheStartTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setNichestarttime(Date nichestarttime) {
        this.nichestarttime = nichestarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_phase.nicheEndTime
     *
     * @return the value of t_banquet_phase.nicheEndTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Date getNicheendtime() {
        return nicheendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_phase.nicheEndTime
     *
     * @param nicheendtime the value for t_banquet_phase.nicheEndTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setNicheendtime(Date nicheendtime) {
        this.nicheendtime = nicheendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_phase.nicheCycleDay
     *
     * @return the value of t_banquet_phase.nicheCycleDay
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Integer getNichecycleday() {
        return nichecycleday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_phase.nicheCycleDay
     *
     * @param nichecycleday the value for t_banquet_phase.nicheCycleDay
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setNichecycleday(Integer nichecycleday) {
        this.nichecycleday = nichecycleday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_phase.intentCreateTime
     *
     * @return the value of t_banquet_phase.intentCreateTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Date getIntentcreatetime() {
        return intentcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_phase.intentCreateTime
     *
     * @param intentcreatetime the value for t_banquet_phase.intentCreateTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setIntentcreatetime(Date intentcreatetime) {
        this.intentcreatetime = intentcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_phase.intentStartTime
     *
     * @return the value of t_banquet_phase.intentStartTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Date getIntentstarttime() {
        return intentstarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_phase.intentStartTime
     *
     * @param intentstarttime the value for t_banquet_phase.intentStartTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setIntentstarttime(Date intentstarttime) {
        this.intentstarttime = intentstarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_phase.intentEndTime
     *
     * @return the value of t_banquet_phase.intentEndTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Date getIntentendtime() {
        return intentendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_phase.intentEndTime
     *
     * @param intentendtime the value for t_banquet_phase.intentEndTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setIntentendtime(Date intentendtime) {
        this.intentendtime = intentendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_phase.intentCycleDay
     *
     * @return the value of t_banquet_phase.intentCycleDay
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Integer getIntentcycleday() {
        return intentcycleday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_phase.intentCycleDay
     *
     * @param intentcycleday the value for t_banquet_phase.intentCycleDay
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setIntentcycleday(Integer intentcycleday) {
        this.intentcycleday = intentcycleday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_phase.priceCreateTime
     *
     * @return the value of t_banquet_phase.priceCreateTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Date getPricecreatetime() {
        return pricecreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_phase.priceCreateTime
     *
     * @param pricecreatetime the value for t_banquet_phase.priceCreateTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setPricecreatetime(Date pricecreatetime) {
        this.pricecreatetime = pricecreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_phase.priceStartTime
     *
     * @return the value of t_banquet_phase.priceStartTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Date getPricestarttime() {
        return pricestarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_phase.priceStartTime
     *
     * @param pricestarttime the value for t_banquet_phase.priceStartTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setPricestarttime(Date pricestarttime) {
        this.pricestarttime = pricestarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_phase.priceEndTime
     *
     * @return the value of t_banquet_phase.priceEndTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Date getPriceendtime() {
        return priceendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_phase.priceEndTime
     *
     * @param priceendtime the value for t_banquet_phase.priceEndTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setPriceendtime(Date priceendtime) {
        this.priceendtime = priceendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_phase.priceCycleDay
     *
     * @return the value of t_banquet_phase.priceCycleDay
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Integer getPricecycleday() {
        return pricecycleday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_phase.priceCycleDay
     *
     * @param pricecycleday the value for t_banquet_phase.priceCycleDay
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setPricecycleday(Integer pricecycleday) {
        this.pricecycleday = pricecycleday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_phase.contractCreateTime
     *
     * @return the value of t_banquet_phase.contractCreateTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Date getContractcreatetime() {
        return contractcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_phase.contractCreateTime
     *
     * @param contractcreatetime the value for t_banquet_phase.contractCreateTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setContractcreatetime(Date contractcreatetime) {
        this.contractcreatetime = contractcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_phase.contractStartTime
     *
     * @return the value of t_banquet_phase.contractStartTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Date getContractstarttime() {
        return contractstarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_phase.contractStartTime
     *
     * @param contractstarttime the value for t_banquet_phase.contractStartTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setContractstarttime(Date contractstarttime) {
        this.contractstarttime = contractstarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_phase.contractEndTime
     *
     * @return the value of t_banquet_phase.contractEndTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Date getContractendtime() {
        return contractendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_phase.contractEndTime
     *
     * @param contractendtime the value for t_banquet_phase.contractEndTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setContractendtime(Date contractendtime) {
        this.contractendtime = contractendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_phase.contractCycleDay
     *
     * @return the value of t_banquet_phase.contractCycleDay
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Integer getContractcycleday() {
        return contractcycleday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_phase.contractCycleDay
     *
     * @param contractcycleday the value for t_banquet_phase.contractCycleDay
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setContractcycleday(Integer contractcycleday) {
        this.contractcycleday = contractcycleday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_phase.prepareCreateTime
     *
     * @return the value of t_banquet_phase.prepareCreateTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Date getPreparecreatetime() {
        return preparecreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_phase.prepareCreateTime
     *
     * @param preparecreatetime the value for t_banquet_phase.prepareCreateTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setPreparecreatetime(Date preparecreatetime) {
        this.preparecreatetime = preparecreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_phase.prepareStartTime
     *
     * @return the value of t_banquet_phase.prepareStartTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Date getPreparestarttime() {
        return preparestarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_phase.prepareStartTime
     *
     * @param preparestarttime the value for t_banquet_phase.prepareStartTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setPreparestarttime(Date preparestarttime) {
        this.preparestarttime = preparestarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_phase.prepareEndTime
     *
     * @return the value of t_banquet_phase.prepareEndTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Date getPrepareendtime() {
        return prepareendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_phase.prepareEndTime
     *
     * @param prepareendtime the value for t_banquet_phase.prepareEndTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setPrepareendtime(Date prepareendtime) {
        this.prepareendtime = prepareendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_phase.prepareCycleDay
     *
     * @return the value of t_banquet_phase.prepareCycleDay
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Integer getPreparecycleday() {
        return preparecycleday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_phase.prepareCycleDay
     *
     * @param preparecycleday the value for t_banquet_phase.prepareCycleDay
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setPreparecycleday(Integer preparecycleday) {
        this.preparecycleday = preparecycleday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_phase.createTime
     *
     * @return the value of t_banquet_phase.createTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_phase.createTime
     *
     * @param createtime the value for t_banquet_phase.createTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_phase.createUserId
     *
     * @return the value of t_banquet_phase.createUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_phase.createUserId
     *
     * @param createuserid the value for t_banquet_phase.createUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setCreateuserid(String createuserid) {
        this.createuserid = createuserid == null ? null : createuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_phase.createUser
     *
     * @return the value of t_banquet_phase.createUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_phase.createUser
     *
     * @param createuser the value for t_banquet_phase.createUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser == null ? null : createuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_phase.updateTime
     *
     * @return the value of t_banquet_phase.updateTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_phase.updateTime
     *
     * @param updatetime the value for t_banquet_phase.updateTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_phase.updateUserId
     *
     * @return the value of t_banquet_phase.updateUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getUpdateuserid() {
        return updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_phase.updateUserId
     *
     * @param updateuserid the value for t_banquet_phase.updateUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setUpdateuserid(String updateuserid) {
        this.updateuserid = updateuserid == null ? null : updateuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_phase.updateUser
     *
     * @return the value of t_banquet_phase.updateUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getUpdateuser() {
        return updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_phase.updateUser
     *
     * @param updateuser the value for t_banquet_phase.updateUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setUpdateuser(String updateuser) {
        this.updateuser = updateuser == null ? null : updateuser.trim();
    }
}