package com.jerry.banquet.model;

import java.util.Date;

public class TBanquetDrinks {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_drinks.drinksId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String drinksid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_drinks.banquetId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String banquetid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_drinks.drinksType
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String drinkstype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_drinks.totalPrice
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Integer totalprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_drinks.remark
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_drinks.createTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_drinks.createUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String createuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_drinks.createUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String createuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_drinks.updateTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_drinks.updateUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String updateuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_drinks.updateUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String updateuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_drinks.drinksId
     *
     * @return the value of t_banquet_drinks.drinksId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getDrinksid() {
        return drinksid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_drinks.drinksId
     *
     * @param drinksid the value for t_banquet_drinks.drinksId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setDrinksid(String drinksid) {
        this.drinksid = drinksid == null ? null : drinksid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_drinks.banquetId
     *
     * @return the value of t_banquet_drinks.banquetId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getBanquetid() {
        return banquetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_drinks.banquetId
     *
     * @param banquetid the value for t_banquet_drinks.banquetId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setBanquetid(String banquetid) {
        this.banquetid = banquetid == null ? null : banquetid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_drinks.drinksType
     *
     * @return the value of t_banquet_drinks.drinksType
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getDrinkstype() {
        return drinkstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_drinks.drinksType
     *
     * @param drinkstype the value for t_banquet_drinks.drinksType
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setDrinkstype(String drinkstype) {
        this.drinkstype = drinkstype == null ? null : drinkstype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_drinks.totalPrice
     *
     * @return the value of t_banquet_drinks.totalPrice
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Integer getTotalprice() {
        return totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_drinks.totalPrice
     *
     * @param totalprice the value for t_banquet_drinks.totalPrice
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setTotalprice(Integer totalprice) {
        this.totalprice = totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_drinks.remark
     *
     * @return the value of t_banquet_drinks.remark
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_drinks.remark
     *
     * @param remark the value for t_banquet_drinks.remark
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_drinks.createTime
     *
     * @return the value of t_banquet_drinks.createTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_drinks.createTime
     *
     * @param createtime the value for t_banquet_drinks.createTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_drinks.createUserId
     *
     * @return the value of t_banquet_drinks.createUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_drinks.createUserId
     *
     * @param createuserid the value for t_banquet_drinks.createUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setCreateuserid(String createuserid) {
        this.createuserid = createuserid == null ? null : createuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_drinks.createUser
     *
     * @return the value of t_banquet_drinks.createUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_drinks.createUser
     *
     * @param createuser the value for t_banquet_drinks.createUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser == null ? null : createuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_drinks.updateTime
     *
     * @return the value of t_banquet_drinks.updateTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_drinks.updateTime
     *
     * @param updatetime the value for t_banquet_drinks.updateTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_drinks.updateUserId
     *
     * @return the value of t_banquet_drinks.updateUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getUpdateuserid() {
        return updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_drinks.updateUserId
     *
     * @param updateuserid the value for t_banquet_drinks.updateUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setUpdateuserid(String updateuserid) {
        this.updateuserid = updateuserid == null ? null : updateuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_drinks.updateUser
     *
     * @return the value of t_banquet_drinks.updateUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getUpdateuser() {
        return updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_drinks.updateUser
     *
     * @param updateuser the value for t_banquet_drinks.updateUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setUpdateuser(String updateuser) {
        this.updateuser = updateuser == null ? null : updateuser.trim();
    }
}