package com.jerry.banquet.model;

import java.util.Date;

public class TBanquetDishes {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_dishes.dishesId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String dishesid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_dishes.banquetId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String banquetid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_dishes.mealDishesId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String mealdishesid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_dishes.dishesName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String dishesname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_dishes.dishesUnit
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String dishesunit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_dishes.dishesNum
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Integer dishesnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_dishes.oriDishesName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String oridishesname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_dishes.oriDishesUnit
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String oridishesunit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_dishes.oriDishesNum
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Integer oridishesnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_dishes.dishesType
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Integer dishestype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_dishes.isDeleted
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Integer isdeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_dishes.createTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_dishes.createUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String createuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_dishes.createUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String createuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_dishes.updateTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_dishes.updateUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String updateuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banquet_dishes.updateUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String updateuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_dishes.dishesId
     *
     * @return the value of t_banquet_dishes.dishesId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getDishesid() {
        return dishesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_dishes.dishesId
     *
     * @param dishesid the value for t_banquet_dishes.dishesId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setDishesid(String dishesid) {
        this.dishesid = dishesid == null ? null : dishesid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_dishes.banquetId
     *
     * @return the value of t_banquet_dishes.banquetId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getBanquetid() {
        return banquetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_dishes.banquetId
     *
     * @param banquetid the value for t_banquet_dishes.banquetId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setBanquetid(String banquetid) {
        this.banquetid = banquetid == null ? null : banquetid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_dishes.mealDishesId
     *
     * @return the value of t_banquet_dishes.mealDishesId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getMealdishesid() {
        return mealdishesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_dishes.mealDishesId
     *
     * @param mealdishesid the value for t_banquet_dishes.mealDishesId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setMealdishesid(String mealdishesid) {
        this.mealdishesid = mealdishesid == null ? null : mealdishesid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_dishes.dishesName
     *
     * @return the value of t_banquet_dishes.dishesName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getDishesname() {
        return dishesname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_dishes.dishesName
     *
     * @param dishesname the value for t_banquet_dishes.dishesName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setDishesname(String dishesname) {
        this.dishesname = dishesname == null ? null : dishesname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_dishes.dishesUnit
     *
     * @return the value of t_banquet_dishes.dishesUnit
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getDishesunit() {
        return dishesunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_dishes.dishesUnit
     *
     * @param dishesunit the value for t_banquet_dishes.dishesUnit
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setDishesunit(String dishesunit) {
        this.dishesunit = dishesunit == null ? null : dishesunit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_dishes.dishesNum
     *
     * @return the value of t_banquet_dishes.dishesNum
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Integer getDishesnum() {
        return dishesnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_dishes.dishesNum
     *
     * @param dishesnum the value for t_banquet_dishes.dishesNum
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setDishesnum(Integer dishesnum) {
        this.dishesnum = dishesnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_dishes.oriDishesName
     *
     * @return the value of t_banquet_dishes.oriDishesName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getOridishesname() {
        return oridishesname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_dishes.oriDishesName
     *
     * @param oridishesname the value for t_banquet_dishes.oriDishesName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setOridishesname(String oridishesname) {
        this.oridishesname = oridishesname == null ? null : oridishesname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_dishes.oriDishesUnit
     *
     * @return the value of t_banquet_dishes.oriDishesUnit
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getOridishesunit() {
        return oridishesunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_dishes.oriDishesUnit
     *
     * @param oridishesunit the value for t_banquet_dishes.oriDishesUnit
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setOridishesunit(String oridishesunit) {
        this.oridishesunit = oridishesunit == null ? null : oridishesunit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_dishes.oriDishesNum
     *
     * @return the value of t_banquet_dishes.oriDishesNum
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Integer getOridishesnum() {
        return oridishesnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_dishes.oriDishesNum
     *
     * @param oridishesnum the value for t_banquet_dishes.oriDishesNum
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setOridishesnum(Integer oridishesnum) {
        this.oridishesnum = oridishesnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_dishes.dishesType
     *
     * @return the value of t_banquet_dishes.dishesType
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Integer getDishestype() {
        return dishestype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_dishes.dishesType
     *
     * @param dishestype the value for t_banquet_dishes.dishesType
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setDishestype(Integer dishestype) {
        this.dishestype = dishestype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_dishes.isDeleted
     *
     * @return the value of t_banquet_dishes.isDeleted
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Integer getIsdeleted() {
        return isdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_dishes.isDeleted
     *
     * @param isdeleted the value for t_banquet_dishes.isDeleted
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setIsdeleted(Integer isdeleted) {
        this.isdeleted = isdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_dishes.createTime
     *
     * @return the value of t_banquet_dishes.createTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_dishes.createTime
     *
     * @param createtime the value for t_banquet_dishes.createTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_dishes.createUserId
     *
     * @return the value of t_banquet_dishes.createUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_dishes.createUserId
     *
     * @param createuserid the value for t_banquet_dishes.createUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setCreateuserid(String createuserid) {
        this.createuserid = createuserid == null ? null : createuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_dishes.createUser
     *
     * @return the value of t_banquet_dishes.createUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_dishes.createUser
     *
     * @param createuser the value for t_banquet_dishes.createUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser == null ? null : createuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_dishes.updateTime
     *
     * @return the value of t_banquet_dishes.updateTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_dishes.updateTime
     *
     * @param updatetime the value for t_banquet_dishes.updateTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_dishes.updateUserId
     *
     * @return the value of t_banquet_dishes.updateUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getUpdateuserid() {
        return updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_dishes.updateUserId
     *
     * @param updateuserid the value for t_banquet_dishes.updateUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setUpdateuserid(String updateuserid) {
        this.updateuserid = updateuserid == null ? null : updateuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banquet_dishes.updateUser
     *
     * @return the value of t_banquet_dishes.updateUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getUpdateuser() {
        return updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banquet_dishes.updateUser
     *
     * @param updateuser the value for t_banquet_dishes.updateUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setUpdateuser(String updateuser) {
        this.updateuser = updateuser == null ? null : updateuser.trim();
    }
}