package com.jerry.banquet.model;

import java.util.Date;

public class TEoRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_eo_record.recordId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String recordid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_eo_record.banquetId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String banquetid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_eo_record.phaseName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String phasename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_eo_record.wordUrl
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String wordurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_eo_record.createTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_eo_record.createUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String createuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_eo_record.createUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String createuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eo_record.recordId
     *
     * @return the value of t_eo_record.recordId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getRecordid() {
        return recordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_eo_record.recordId
     *
     * @param recordid the value for t_eo_record.recordId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setRecordid(String recordid) {
        this.recordid = recordid == null ? null : recordid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eo_record.banquetId
     *
     * @return the value of t_eo_record.banquetId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getBanquetid() {
        return banquetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_eo_record.banquetId
     *
     * @param banquetid the value for t_eo_record.banquetId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setBanquetid(String banquetid) {
        this.banquetid = banquetid == null ? null : banquetid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eo_record.phaseName
     *
     * @return the value of t_eo_record.phaseName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getPhasename() {
        return phasename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_eo_record.phaseName
     *
     * @param phasename the value for t_eo_record.phaseName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setPhasename(String phasename) {
        this.phasename = phasename == null ? null : phasename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eo_record.wordUrl
     *
     * @return the value of t_eo_record.wordUrl
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getWordurl() {
        return wordurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_eo_record.wordUrl
     *
     * @param wordurl the value for t_eo_record.wordUrl
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setWordurl(String wordurl) {
        this.wordurl = wordurl == null ? null : wordurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eo_record.createTime
     *
     * @return the value of t_eo_record.createTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_eo_record.createTime
     *
     * @param createtime the value for t_eo_record.createTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eo_record.createUserId
     *
     * @return the value of t_eo_record.createUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_eo_record.createUserId
     *
     * @param createuserid the value for t_eo_record.createUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setCreateuserid(String createuserid) {
        this.createuserid = createuserid == null ? null : createuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eo_record.createUser
     *
     * @return the value of t_eo_record.createUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_eo_record.createUser
     *
     * @param createuser the value for t_eo_record.createUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser == null ? null : createuser.trim();
    }
}