package com.jerry.banquet.model;

public class TOutExtChannel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_out_ext_channel.channelID
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String channelid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_out_ext_channel.restaurantID
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String restaurantid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_out_ext_channel.restaurantName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String restaurantname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_out_ext_channel.externalChannelId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String externalchannelid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_out_ext_channel.externalChannelName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String externalchannelname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_out_ext_channel.isExternalChannel
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Integer isexternalchannel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_out_ext_channel.channelID
     *
     * @return the value of t_out_ext_channel.channelID
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getChannelid() {
        return channelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_out_ext_channel.channelID
     *
     * @param channelid the value for t_out_ext_channel.channelID
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setChannelid(String channelid) {
        this.channelid = channelid == null ? null : channelid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_out_ext_channel.restaurantID
     *
     * @return the value of t_out_ext_channel.restaurantID
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getRestaurantid() {
        return restaurantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_out_ext_channel.restaurantID
     *
     * @param restaurantid the value for t_out_ext_channel.restaurantID
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setRestaurantid(String restaurantid) {
        this.restaurantid = restaurantid == null ? null : restaurantid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_out_ext_channel.restaurantName
     *
     * @return the value of t_out_ext_channel.restaurantName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getRestaurantname() {
        return restaurantname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_out_ext_channel.restaurantName
     *
     * @param restaurantname the value for t_out_ext_channel.restaurantName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setRestaurantname(String restaurantname) {
        this.restaurantname = restaurantname == null ? null : restaurantname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_out_ext_channel.externalChannelId
     *
     * @return the value of t_out_ext_channel.externalChannelId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getExternalchannelid() {
        return externalchannelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_out_ext_channel.externalChannelId
     *
     * @param externalchannelid the value for t_out_ext_channel.externalChannelId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setExternalchannelid(String externalchannelid) {
        this.externalchannelid = externalchannelid == null ? null : externalchannelid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_out_ext_channel.externalChannelName
     *
     * @return the value of t_out_ext_channel.externalChannelName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getExternalchannelname() {
        return externalchannelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_out_ext_channel.externalChannelName
     *
     * @param externalchannelname the value for t_out_ext_channel.externalChannelName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setExternalchannelname(String externalchannelname) {
        this.externalchannelname = externalchannelname == null ? null : externalchannelname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_out_ext_channel.isExternalChannel
     *
     * @return the value of t_out_ext_channel.isExternalChannel
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Integer getIsexternalchannel() {
        return isexternalchannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_out_ext_channel.isExternalChannel
     *
     * @param isexternalchannel the value for t_out_ext_channel.isExternalChannel
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setIsexternalchannel(Integer isexternalchannel) {
        this.isexternalchannel = isexternalchannel;
    }
}