package com.jerry.banquet.model;

import java.util.Date;

public class TOutDesk {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_out_desk.deskID
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String deskid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_out_desk.areaID
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String areaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_out_desk.restaurantID
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String restaurantid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_out_desk.deskName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String deskname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_out_desk.peopleMin
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Integer peoplemin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_out_desk.peopleMax
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Integer peoplemax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_out_desk.remark
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_out_desk.freezeFlag
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Integer freezeflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_out_desk.sequence
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Integer sequence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_out_desk.createTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_out_desk.deskID
     *
     * @return the value of t_out_desk.deskID
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getDeskid() {
        return deskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_out_desk.deskID
     *
     * @param deskid the value for t_out_desk.deskID
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setDeskid(String deskid) {
        this.deskid = deskid == null ? null : deskid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_out_desk.areaID
     *
     * @return the value of t_out_desk.areaID
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getAreaid() {
        return areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_out_desk.areaID
     *
     * @param areaid the value for t_out_desk.areaID
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setAreaid(String areaid) {
        this.areaid = areaid == null ? null : areaid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_out_desk.restaurantID
     *
     * @return the value of t_out_desk.restaurantID
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getRestaurantid() {
        return restaurantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_out_desk.restaurantID
     *
     * @param restaurantid the value for t_out_desk.restaurantID
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setRestaurantid(String restaurantid) {
        this.restaurantid = restaurantid == null ? null : restaurantid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_out_desk.deskName
     *
     * @return the value of t_out_desk.deskName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getDeskname() {
        return deskname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_out_desk.deskName
     *
     * @param deskname the value for t_out_desk.deskName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setDeskname(String deskname) {
        this.deskname = deskname == null ? null : deskname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_out_desk.peopleMin
     *
     * @return the value of t_out_desk.peopleMin
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Integer getPeoplemin() {
        return peoplemin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_out_desk.peopleMin
     *
     * @param peoplemin the value for t_out_desk.peopleMin
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setPeoplemin(Integer peoplemin) {
        this.peoplemin = peoplemin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_out_desk.peopleMax
     *
     * @return the value of t_out_desk.peopleMax
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Integer getPeoplemax() {
        return peoplemax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_out_desk.peopleMax
     *
     * @param peoplemax the value for t_out_desk.peopleMax
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setPeoplemax(Integer peoplemax) {
        this.peoplemax = peoplemax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_out_desk.remark
     *
     * @return the value of t_out_desk.remark
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_out_desk.remark
     *
     * @param remark the value for t_out_desk.remark
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_out_desk.freezeFlag
     *
     * @return the value of t_out_desk.freezeFlag
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Integer getFreezeflag() {
        return freezeflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_out_desk.freezeFlag
     *
     * @param freezeflag the value for t_out_desk.freezeFlag
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setFreezeflag(Integer freezeflag) {
        this.freezeflag = freezeflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_out_desk.sequence
     *
     * @return the value of t_out_desk.sequence
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_out_desk.sequence
     *
     * @param sequence the value for t_out_desk.sequence
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_out_desk.createTime
     *
     * @return the value of t_out_desk.createTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_out_desk.createTime
     *
     * @param createtime the value for t_out_desk.createTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}