package com.jerry.banquet.model;

import java.util.Date;

public class TSysEmployee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_employee.id
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_employee.empId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String empid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_employee.empName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String empname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_employee.channelId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String channelid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_employee.departId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String departid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_employee.departName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String departname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_employee.restaurantId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String restaurantid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_employee.restaurantName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String restaurantname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_employee.isValid
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Integer isvalid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_employee.createTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_employee.createUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String createuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_employee.createUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String createuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_employee.updateTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_employee.updateUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String updateuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_employee.updateUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    private String updateuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_employee.id
     *
     * @return the value of t_sys_employee.id
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_employee.id
     *
     * @param id the value for t_sys_employee.id
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_employee.empId
     *
     * @return the value of t_sys_employee.empId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getEmpid() {
        return empid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_employee.empId
     *
     * @param empid the value for t_sys_employee.empId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setEmpid(String empid) {
        this.empid = empid == null ? null : empid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_employee.empName
     *
     * @return the value of t_sys_employee.empName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getEmpname() {
        return empname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_employee.empName
     *
     * @param empname the value for t_sys_employee.empName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setEmpname(String empname) {
        this.empname = empname == null ? null : empname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_employee.channelId
     *
     * @return the value of t_sys_employee.channelId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getChannelid() {
        return channelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_employee.channelId
     *
     * @param channelid the value for t_sys_employee.channelId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setChannelid(String channelid) {
        this.channelid = channelid == null ? null : channelid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_employee.departId
     *
     * @return the value of t_sys_employee.departId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getDepartid() {
        return departid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_employee.departId
     *
     * @param departid the value for t_sys_employee.departId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setDepartid(String departid) {
        this.departid = departid == null ? null : departid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_employee.departName
     *
     * @return the value of t_sys_employee.departName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getDepartname() {
        return departname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_employee.departName
     *
     * @param departname the value for t_sys_employee.departName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setDepartname(String departname) {
        this.departname = departname == null ? null : departname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_employee.restaurantId
     *
     * @return the value of t_sys_employee.restaurantId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getRestaurantid() {
        return restaurantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_employee.restaurantId
     *
     * @param restaurantid the value for t_sys_employee.restaurantId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setRestaurantid(String restaurantid) {
        this.restaurantid = restaurantid == null ? null : restaurantid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_employee.restaurantName
     *
     * @return the value of t_sys_employee.restaurantName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getRestaurantname() {
        return restaurantname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_employee.restaurantName
     *
     * @param restaurantname the value for t_sys_employee.restaurantName
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setRestaurantname(String restaurantname) {
        this.restaurantname = restaurantname == null ? null : restaurantname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_employee.isValid
     *
     * @return the value of t_sys_employee.isValid
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Integer getIsvalid() {
        return isvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_employee.isValid
     *
     * @param isvalid the value for t_sys_employee.isValid
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setIsvalid(Integer isvalid) {
        this.isvalid = isvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_employee.createTime
     *
     * @return the value of t_sys_employee.createTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_employee.createTime
     *
     * @param createtime the value for t_sys_employee.createTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_employee.createUserId
     *
     * @return the value of t_sys_employee.createUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_employee.createUserId
     *
     * @param createuserid the value for t_sys_employee.createUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setCreateuserid(String createuserid) {
        this.createuserid = createuserid == null ? null : createuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_employee.createUser
     *
     * @return the value of t_sys_employee.createUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_employee.createUser
     *
     * @param createuser the value for t_sys_employee.createUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser == null ? null : createuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_employee.updateTime
     *
     * @return the value of t_sys_employee.updateTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_employee.updateTime
     *
     * @param updatetime the value for t_sys_employee.updateTime
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_employee.updateUserId
     *
     * @return the value of t_sys_employee.updateUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getUpdateuserid() {
        return updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_employee.updateUserId
     *
     * @param updateuserid the value for t_sys_employee.updateUserId
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setUpdateuserid(String updateuserid) {
        this.updateuserid = updateuserid == null ? null : updateuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_employee.updateUser
     *
     * @return the value of t_sys_employee.updateUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public String getUpdateuser() {
        return updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_employee.updateUser
     *
     * @param updateuser the value for t_sys_employee.updateUser
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    public void setUpdateuser(String updateuser) {
        this.updateuser = updateuser == null ? null : updateuser.trim();
    }
}