package com.jerry.banquet.mapper;

import com.jerry.banquet.model.TBanquetDesk;

public interface TBanquetDeskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_desk
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int deleteByPrimaryKey(String banquetdeskid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_desk
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int insert(TBanquetDesk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_desk
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int insertSelective(TBanquetDesk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_desk
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    TBanquetDesk selectByPrimaryKey(String banquetdeskid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_desk
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int updateByPrimaryKeySelective(TBanquetDesk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_desk
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int updateByPrimaryKey(TBanquetDesk record);
}