package com.jerry.banquet.mapper;

import com.jerry.banquet.model.TBanquetMemorandum;

public interface TBanquetMemorandumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_memorandum
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int deleteByPrimaryKey(String memorandumid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_memorandum
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int insert(TBanquetMemorandum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_memorandum
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int insertSelective(TBanquetMemorandum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_memorandum
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    TBanquetMemorandum selectByPrimaryKey(String memorandumid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_memorandum
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int updateByPrimaryKeySelective(TBanquetMemorandum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_memorandum
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int updateByPrimaryKey(TBanquetMemorandum record);
}