package com.jerry.banquet.mapper;

import com.jerry.banquet.model.TBanquetOrderField;

public interface TBanquetOrderFieldMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_order_field
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int deleteByPrimaryKey(String fieldid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_order_field
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int insert(TBanquetOrderField record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_order_field
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int insertSelective(TBanquetOrderField record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_order_field
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    TBanquetOrderField selectByPrimaryKey(String fieldid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_order_field
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int updateByPrimaryKeySelective(TBanquetOrderField record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_order_field
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int updateByPrimaryKey(TBanquetOrderField record);
}