package com.jerry.banquet.mapper;

import com.jerry.banquet.model.TBanquetContract;

public interface TBanquetContractMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_contract
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int deleteByPrimaryKey(String banquetid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_contract
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int insert(TBanquetContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_contract
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int insertSelective(TBanquetContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_contract
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    TBanquetContract selectByPrimaryKey(String banquetid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_contract
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int updateByPrimaryKeySelective(TBanquetContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_contract
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int updateByPrimaryKey(TBanquetContract record);
}