package com.jerry.banquet.mapper;

import com.jerry.banquet.model.TBanquetTimesheet;

public interface TBanquetTimesheetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_timesheet
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int deleteByPrimaryKey(String timesheetid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_timesheet
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int insert(TBanquetTimesheet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_timesheet
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int insertSelective(TBanquetTimesheet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_timesheet
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    TBanquetTimesheet selectByPrimaryKey(String timesheetid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_timesheet
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int updateByPrimaryKeySelective(TBanquetTimesheet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_timesheet
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int updateByPrimaryKey(TBanquetTimesheet record);
}