package com.jerry.banquet.mapper;

import com.jerry.banquet.model.TBanquetLog;

public interface TBanquetLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_log
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int deleteByPrimaryKey(String logid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_log
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int insert(TBanquetLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_log
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int insertSelective(TBanquetLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_log
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    TBanquetLog selectByPrimaryKey(String logid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_log
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int updateByPrimaryKeySelective(TBanquetLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_log
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int updateByPrimaryKey(TBanquetLog record);
}