package com.jerry.banquet.mapper;

import java.util.List;

import com.jerry.banquet.model.TBanquet;
import com.jerry.banquet.model.TBanquetAffix;

public interface TBanquetAffixMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_affix
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int deleteByPrimaryKey(String affixid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_affix
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int insert(TBanquetAffix record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_affix
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int insertSelective(TBanquetAffix record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_affix
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    TBanquetAffix selectByPrimaryKey(String affixid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_affix
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int updateByPrimaryKeySelective(TBanquetAffix record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_affix
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int updateByPrimaryKey(TBanquetAffix record);
}