package com.jerry.banquet.mapper;

import com.jerry.banquet.model.TBanquetFacility;

public interface TBanquetFacilityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_facility
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int deleteByPrimaryKey(String banquetfacilityid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_facility
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int insert(TBanquetFacility record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_facility
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int insertSelective(TBanquetFacility record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_facility
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    TBanquetFacility selectByPrimaryKey(String banquetfacilityid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_facility
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int updateByPrimaryKeySelective(TBanquetFacility record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_facility
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int updateByPrimaryKey(TBanquetFacility record);
}