package com.jerry.banquet.mapper;

import java.util.List;

import com.jerry.banquet.model.TBanquet;

public interface TBanquetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    int deleteByPrimaryKey(String banquetid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    int insert(TBanquet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    int insertSelective(TBanquet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    TBanquet selectByPrimaryKey(String banquetid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    int updateByPrimaryKeySelective(TBanquet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet
     *
     * @mbg.generated Wed Aug 22 17:51:12 CST 2018
     */
    int updateByPrimaryKey(TBanquet record);
    
    /**获取所有的宴会
     * @return
     */
    List<TBanquet> listBanquets();
}