package com.jerry.banquet.mapper;

import com.jerry.banquet.model.TBanquetOrderTemplate;

public interface TBanquetOrderTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_order_template
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int deleteByPrimaryKey(String templateid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_order_template
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int insert(TBanquetOrderTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_order_template
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int insertSelective(TBanquetOrderTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_order_template
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    TBanquetOrderTemplate selectByPrimaryKey(String templateid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_order_template
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int updateByPrimaryKeySelective(TBanquetOrderTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_order_template
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int updateByPrimaryKey(TBanquetOrderTemplate record);
}