package com.jerry.banquet.mapper;

import com.jerry.banquet.model.TBanquetOrder;

public interface TBanquetOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_order
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int deleteByPrimaryKey(String orderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_order
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int insert(TBanquetOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_order
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int insertSelective(TBanquetOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_order
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    TBanquetOrder selectByPrimaryKey(String orderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_order
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int updateByPrimaryKeySelective(TBanquetOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banquet_order
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int updateByPrimaryKey(TBanquetOrder record);
}