package com.jerry.banquet.mapper;

import com.jerry.banquet.model.TEoRecord;

public interface TEoRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eo_record
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int deleteByPrimaryKey(String recordid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eo_record
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int insert(TEoRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eo_record
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int insertSelective(TEoRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eo_record
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    TEoRecord selectByPrimaryKey(String recordid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eo_record
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int updateByPrimaryKeySelective(TEoRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eo_record
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int updateByPrimaryKey(TEoRecord record);
}