package com.jerry.banquet.mapper;

import com.jerry.banquet.model.TOutDesk;

public interface TOutDeskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_out_desk
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int deleteByPrimaryKey(String deskid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_out_desk
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int insert(TOutDesk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_out_desk
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int insertSelective(TOutDesk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_out_desk
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    TOutDesk selectByPrimaryKey(String deskid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_out_desk
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int updateByPrimaryKeySelective(TOutDesk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_out_desk
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int updateByPrimaryKey(TOutDesk record);
}