package com.jerry.banquet.mapper;

import com.jerry.banquet.model.TOutBanquetType;

public interface TOutBanquetTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_out_banquet_type
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int deleteByPrimaryKey(String typeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_out_banquet_type
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int insert(TOutBanquetType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_out_banquet_type
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int insertSelective(TOutBanquetType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_out_banquet_type
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    TOutBanquetType selectByPrimaryKey(String typeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_out_banquet_type
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int updateByPrimaryKeySelective(TOutBanquetType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_out_banquet_type
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int updateByPrimaryKey(TOutBanquetType record);
}