package com.jerry.banquet.mapper;

import com.jerry.banquet.model.TOutExtChannel;

public interface TOutExtChannelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_out_ext_channel
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int deleteByPrimaryKey(String channelid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_out_ext_channel
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int insert(TOutExtChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_out_ext_channel
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int insertSelective(TOutExtChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_out_ext_channel
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    TOutExtChannel selectByPrimaryKey(String channelid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_out_ext_channel
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int updateByPrimaryKeySelective(TOutExtChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_out_ext_channel
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int updateByPrimaryKey(TOutExtChannel record);
}