package com.jerry.banquet.mapper;

import com.jerry.banquet.model.TSysSetmeal;

public interface TSysSetmealMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_setmeal
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int deleteByPrimaryKey(String setmealid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_setmeal
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int insert(TSysSetmeal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_setmeal
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int insertSelective(TSysSetmeal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_setmeal
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    TSysSetmeal selectByPrimaryKey(String setmealid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_setmeal
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int updateByPrimaryKeySelective(TSysSetmeal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_setmeal
     *
     * @mbg.generated Wed Aug 22 17:51:13 CST 2018
     */
    int updateByPrimaryKey(TSysSetmeal record);
}